# aws cloudformation update-stack --stack-name cfn-demo-s3 --template-body file://3-changing-name.yaml
# aws cloudformation delete-stack --stack-name cfn-demo-s3
---
AWSTemplateFormatVersion: "2010-09-09"

Description:
  Simple public S3 bucket

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: "dsf-s3-231029"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
      OwnershipControls:
        Rules:
          - ObjectOwnership: ObjectWriter
