---
AWSTemplateFormatVersion: "2010-09-09"
Description: "CloudFormation template to create an SSM Document for installing Libreswan"

Resources:
  LibreswanConfigureSSMDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        description: "Configure IPSEC connection on instance."
        parameters:
          IpsecLeftId:
            type: String
            description: "Id of the left IPSEC"
            default: ''
          IpsecRightId:
            type: String
            description: "Id of the right IPSEC"
            default: ''
          IpsecLeftCidr:
            type: String
            description: "CIDR of the left IPSEC"
            default: ''
          IpsecRightCidr:
            type: String
            description: "CIDR of the right IPSEC"
            default: ''
          IpsecSecret:
            type: String
            description: "Secret of the IPSEC"
            default: ''
        mainSteps:
        - name: IpsecConfiguration
          action: aws:runShellScript
          inputs:
            timeoutSeconds: '60'
            runCommand:
              - |
                  cat << EOF > /etc/ipsec.d/aws.conf
                  conn Tunnel1
                    authby=secret
                    auto=start
                    left=%defaultroute
                    leftid={{IpsecLeftId}}
                    right={{IpsecRightId}}
                    type=tunnel
                    ikelifetime=8h
                    keylife=1h
                    phase2alg=aes256-sha1;modp2048
                    ike=aes256-sha1;modp2048
                    keyingtries=%forever
                    keyexchange=ike
                    leftsubnet={{IpsecLeftCidr}}
                    rightsubnet={{IpsecRightCidr}}
                    dpddelay=10
                    dpdtimeout=30
                    dpdaction=restart_by_peer
                    encapsulation=yes
                  EOF
        - name: IpsecSecret
          action: aws:runShellScript          
          inputs:
            timeoutSeconds: '60'
            runCommand:
              - |
                  cat << EOF > /etc/ipsec.d/aws.secrets
                  {{IpsecLeftId}} {{IpsecRightId}}: PSK "{{IpsecSecret}}"
                  EOF
        - name: IpsecStart
          action: aws:runShellScript          
          inputs:
            timeoutSeconds: '60'
            runCommand:
              - systemctl start ipsec.service
              - systemctl enable ipsec.service
              - systemctl status ipsec.service
        schemaVersion: "2.2"
      DocumentFormat: YAML
      DocumentType: Command
      Name: LibreswanConfigureSSMDocument
      TargetType: "/AWS::EC2::Instance"
      UpdateMethod: Replace