---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Association for OpenVPN EasyRSA SSM Document"

Parameters:
  # Global parameters
  Bucket:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    Default: "hawkfund-cloudformation"
    Description: CloudFormation bucket URL
    Type: String
  BucketKey:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    Default: "110_AWSClientVpn"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  BucketRegion:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    AllowedValues: ["eu-west-3", "eu-central-1"]
    Default: "eu-west-3"
    Description: "Region where is the Bucket"
    Type: String
  EnvironmentName:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    AllowedValues: ["dev", "test", "prod"]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefixes all resources"
    Type: String
  ProjectName:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    ConstraintDescription: "Must be 1-20 characters"
    Default: "OpenVPN"
    Description: "Project name that prefixes all resources"
    MinLength: 1
    MaxLength: 20
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  AssociationName:
    Default: "OpenVpnEasyRsaSsmAssociation"
    Description: "Specify a descriptive name for the association."
    Type: String
  RootCaName:
    Default: "OpenVPN-CA"
    Description: "Default CA certificate name"
    MaxLength: 64
    MinLength: 1
    Type: String
  ClientBaseName: 
    AllowedPattern: "^[a-zA-Z0-9._-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters, periods, hyphens, and underscores"
    Default: "client1.domain.kr"
    Description: "Default client certificate base name"
    MaxLength: 64
    MinLength: 1
    Type: String
  InstanceId:
    Description: "ID of the EC2 instance"
    Type: String
  Name:
    AllowedPattern: "^[a-zA-Z0-9_.-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters, hyphens, periods, and underscores"
    Description: "Name of the SSM Document"
    Default: "OpenVpnEasyRsaInstaller"
    MaxLength: 64
    MinLength: 3
    Type: String
  OutputS3BucketName:
    Description: "The Bucket name for logs"
    Type: String
  OutputS3KeyPrefix:
    Default: "logs/"
    Description: "Logs prefix"
    Type: String
  ServerBaseName:
    AllowedPattern: "^[a-zA-Z0-9._-]+$"
    ConstraintDescription: "Must contain only alphanumeric characters, periods, hyphens, and underscores"
    Default: "application"
    Description: "Default server certificate base name"
    MaxLength: 64
    MinLength: 1
    Type: String

Conditions:
  SaveInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  AssociationWaitConditionHandle:
    Type: AWS::CloudFormation::WaitConditionHandle

  AssociationWaitCondition:
    Type: AWS::CloudFormation::WaitCondition
    DependsOn: 
      - Association
    Properties:
      Count: 1
      Handle: !Ref AssociationWaitConditionHandle
      Timeout: 600

  Association:
    Type: AWS::SSM::Association
    Properties:
      AssociationName: !Ref AssociationName
      Name: !Sub "${ProjectName}-${EnvironmentName}-${Name}"
      OutputLocation:
        S3Location:
          OutputS3BucketName: !Ref OutputS3BucketName
          OutputS3KeyPrefix: !Ref OutputS3KeyPrefix
      Parameters:
        Bucket:
          - !Ref Bucket
        BucketKey:
          - !Ref BucketKey
        ProjectName:
          - !Ref ProjectName
        EnvironmentName: 
          - !Ref EnvironmentName
        RootCaName:
          - !Ref RootCaName
        ClientBaseName: 
          - !Ref ClientBaseName
        StackName: 
          - !Ref AWS::StackName
        Region: 
          - !Ref AWS::Region
        ResourceName:
          - "AssociationWaitCondition"
        ServerBaseName:
          - !Ref ServerBaseName
        WaitHandleUrl:
          - !Ref AssociationWaitConditionHandle
        InstallDirectory:
          - "/opt/openvpn-setup"
        CertificatesDirectory:
          - "/opt/certificates"
      Targets:
      - Key: InstanceIds
        Values:
        - !Ref InstanceId
