---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys a VPC, Public and Private Subnets

Parameters:
  VPCName:
    Description: VPC name
    Type: String
  VPCCidr:
    Description: VPC CIDR
    Type: String
  SubnetName:
    Description: Subnet name
    Type: String
  PrivateSubnetCidr:
    Description: Private Subnet CIDR
    Type: String
  PublicSubnetCidr:
    Description: Public Subnet CIDR
    Type: String

Resources:
  # VPC, DHCPOptions, Association and App and DB Subnets
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidr
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Ref VPCName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: !Ref PublicSubnetCidr
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub "${SubnetName}-Public"

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: !Ref PrivateSubnetCidr
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Sub "${SubnetName}-Private"

Outputs:
  VpcId:
    Description: "Id of the VPC"
    Value: !Ref VPC
  PublicSubnetId:
    Description: "Id of the Public subnet"
    Value: !Ref PublicSubnet
  PrivateSubnetId:
    Description: "Id of the Private subnet"
    Value: !Ref PrivateSubnet
