---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create SQS Queue

Parameters:
  QueueName:
    Description: SQS queue name
    Type: String
  QueueMessageRetentionPeriod:
    Description: SQS queue message retention period in second
    Type: Number

Resources: 
  Queue: 
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: !Ref QueueMessageRetentionPeriod
      QueueName: !Ref QueueName

Outputs: 
  QueueURL: 
    Description: "URL of new Amazon SQS Queue"
    Value: !Ref Queue
  QueueARN: 
    Description: "ARN of new AmazonSQS Queue"
    Value: !GetAtt  Queue.Arn