---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a role for S3 Gateway Endpoint

Parameters:
  QueueARN:
    Type: String

Resources:
  PrivateInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Private-Instance-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  PrivateInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: Private-Instance-Profile
      Path: /
      Roles: 
       - !Ref PrivateInstanceRole

  InstanceSQSPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: SQS-Allow-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - "sqs:SendMessage"
            Resource:
              - !Ref QueueARN
      Roles:
        - !Ref PrivateInstanceRole


Outputs:
  PrivateInstanceRoleId:
    Description: ID of the Private Instance Role
    Value: !Ref PrivateInstanceRole
  PrivateInstanceProfileId:
    Description: ID of the Private Instance Profile
    Value: !Ref PrivateInstanceProfile
  InstanceSQSPolicyId:
    Description: ID of the Instance S3 Policy
    Value: !Ref InstanceSQSPolicy
