# aws cloudformation validate-template --template-body file:/58_ROOT_VPCInterfaceEndpointForSQS.yaml
# aws cloudformation create-stack --stack-name ANS-58 --template-body file:/58_ROOT_VPCInterfaceEndpointForSQS.yaml --region eu-west-3 --capabilities CAPABILITY_IAM
# aws cloudformation delete-stack --stack-name ANS-58 --region eu-west-3
#
# aws sqs send-message --queue-url https://sqs.eu-west-3.amazonaws.com/${AWS::Region}/My-Queue --message-body "Information about the largest city in Any Region." --delay-seconds 10 --message-attributes file://send-message.json
AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys a VPC, Public and Private Subnets, Bastion, application server and Interface Endpoint for SQS

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "VPC configuration"
        Parameters:
          - VPCName
          - VpcCidrBlock
      - Label:
          default: "Subnets configuration"
        Parameters:
          - SubnetName
          - PrivateSubnetCidr
          - PublicSubnetCidr
      - Label:
          default: "IGW, Route Tables and Routes"
        Parameters:
          - InternetGatewayName
          - RouteTableName
      - Label:
          default: "Queue"
        Parameters:
          - QueueName
          - QueueMessageRetentionPeriod
      - Label:
          default: "Instances"
        Parameters:
          - InstanceImageId
          - InstanceKeyName
          - PrivateInstanceName
          - PublicInstanceName
      - Label:
          default: "Configuration"
        Parameters:
          - Bucket
          - BucketKey

Parameters:
  VPCName:
    Description: "VPC name"
    Type: String
    Default: "My-VPC"
  VpcCidrBlock:
    Description: "The IPv4 network range for the VPC, in CIDR notation."
    Type: String
    Default: 10.10.0.0/16

  SubnetName:
    Description: Subnet name
    Type: String
    Default: "Subnet"
  PrivateSubnetCidr:
    Description: "Private Subnet CIDR"
    Type: String
    Default: 10.10.1.0/24
  PublicSubnetCidr:
    Description: "Public Subnet CIDR"
    Type: String
    Default: 10.10.0.0/24

  QueueName:
    Description: SQS queue name
    Type: String
    Default: "My-Queue"
  QueueMessageRetentionPeriod:
    Description: "SQS queue message retention period in second"
    Type: Number
    Default: 60

  InternetGatewayName:
    Type: String
    Default: "VPC-IGW"
  RouteTableName:
    Type: String
    Default: "VPC-RT"
 
  InstanceImageId:
    Description: Instance AMI
    Type: AWS::EC2::Image::Id
    Default: ami-015875403620174eb
  InstanceKeyName: 
    Description: Instance Key name
    Type: String
    Default: "dso-paris"
  PrivateInstanceName: 
    Description: Private instance name
    Type: String
    Default: "My-Application"
  PublicInstanceName: 
    Description: Public instance name
    Type: String
    Default: "Bastion"

  Bucket:
    Description: CloudFormation buket URL
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
    Default: "58_VPCInterfaceEndPointForSQS"

Resources:
  VPCAndSubnets:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_20_VPCAndSubnets.yaml"
      TimeoutInMinutes: 5
      Parameters:
        VPCName: !Ref VPCName
        VpcCidrBlock: !Ref VpcCidrBlock
        SubnetName: !Ref SubnetName
        PrivateSubnetCidr: !Ref PrivateSubnetCidr
        PublicSubnetCidr: !Ref PublicSubnetCidr

  SQS:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_30_SQS.yaml"
      TimeoutInMinutes: 5
      Parameters:
        QueueName: !Ref QueueName
        QueueMessageRetentionPeriod: !Ref QueueMessageRetentionPeriod

  Roles:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_40_Roles.yaml"
      TimeoutInMinutes: 5
      Parameters:
        QueueARN: !GetAtt SQS.Outputs.QueueARN

# Create Internet Gateway and default route table for public subnet
  InternetGateways:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_50_Gateways.yaml"
      TimeoutInMinutes: 5
      Parameters:
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        InternetGatewayName:  !Ref InternetGatewayName

  RouteTables:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_60_RouteTables.yaml"
      TimeoutInMinutes: 5
      Parameters:
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        PrivateSubnetId: !GetAtt VPCAndSubnets.Outputs.PrivateSubnetId
        PublicSubnetId: !GetAtt VPCAndSubnets.Outputs.PublicSubnetId
        InternetGatewayId:  !GetAtt InternetGateways.Outputs.InternetGatewayId
        RouteTableName: !Ref RouteTableName

  Endpoints:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_70_Endpoints.yaml"
      TimeoutInMinutes: 5
      Parameters:
        QueueARN: !GetAtt SQS.Outputs.QueueARN
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        VpcCidrBlock: !Ref VpcCidrBlock
        PrivateSubnetId: !GetAtt VPCAndSubnets.Outputs.PrivateSubnetId

  Instances:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/58_80_Instances.yaml"
      TimeoutInMinutes: 5
      Parameters:
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        PrivateSubnetId: !GetAtt VPCAndSubnets.Outputs.PrivateSubnetId
        PublicSubnetId: !GetAtt VPCAndSubnets.Outputs.PublicSubnetId
        InstanceImageId: !Ref InstanceImageId
        PrivateInstanceName: !Ref PrivateInstanceName
        PublicInstanceName: !Ref PublicInstanceName
        InstanceKeyName: !Ref InstanceKeyName
        PrivateSourceCidr: !Ref VpcCidrBlock
        PublicSourceCidr: "0.0.0.0/0"
        PrivateInstanceProfile: !GetAtt Roles.Outputs.PrivateInstanceProfileId
  