---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a role for remote account to create VPC Peering

Parameters:
  # Global parameters
  Bucket:
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Description: File in the bucket that contain parameters
    Type: String

  # Stack parameters
  FirstAccountId:
    Description: First AWS Account ID for VPC peering
    Type: String
  PeerRequesterAccountId:
    Description: Second AWS Account ID for VPC peering
    Type: String

Resources:
  PeerRole:
    Type: 'AWS::IAM::Role'
    Properties: 
      AssumeRolePolicyDocument:
        Statement:
          - Principal:
              AWS: !Ref PeerRequesterAccountId
            Action:
              - 'sts:AssumeRole'
            Effect: Allow
      Path: /
      Policies:
        - PolicyName: PeerRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 'ec2:AcceptVpcPeeringConnection'
                Resource: '*'
      Tags:
           - Key: Name
             Value: PeerRole

  PeerRoleBackup:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: "PeerRoleArn"
      Value: !GetAtt PeerRole.Arn      

Outputs:
  PeerRoleArn:
    Description: ARN of th Peering Role
    Value: !GetAtt PeerRole.Arn
  PeerRequesterAccountId:
    Description: PeerRequesterAccountId
    Value: !Ref PeerRequesterAccountId
  FirstAccountId:
    Description: FirstAccountId
    Value: !Ref FirstAccountId
