# aws cloudformation validate-template --template-body file:/50_VPCPeeringAcrossAccount.yaml
# aws cloudformation create-stack --stack-name ANS-50 --template-body file://50_ROOT_VPCPeeringAcrossAccount.yaml --region eu-west-3 --capabilities CAPABILITY_IAM
# aws cloudformation create-stack --stack-name ANS-50 --template-body file://50_ROOT_VPCPeeringAcrossAccount.yaml --region eu-central-1 --capabilities CAPABILITY_IAM
# aws cloudformation delete-stack --stack-name ANS-50 --region eu-west-3
# aws cloudformation delete-stack --stack-name ANS-50 --region eu-central-1
#
# Steps:
# 1 - Launch Phase1 on account 1
# 1 - Launch Phase1 on account 2
# 1 - Launch Phase2 on account 1
# 1 - Launch Phase2 on account 2


AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys a VPC, Public and Private Subnets, Internet Gateway, Route Table, Custom DNS and Instances

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Configuration"
        Parameters:
          - Phase
          - Bucket
          - BucketKey
          - BucketObject
      - Label:
          default: "First Accounts"
        Parameters:
          - FirstAccountId
          - FirstRegion
      - Label:
          default: "Second Accounts"
        Parameters:
          - SecondAccountId
          - SecondRegion
      - Label:
          default: "IGW, Route Tables and Routes"
        Parameters:
          - InternetGatewayName
          - DefaultRouteTableName

Parameters:
  Bucket:
    Description: CloudFormation buket URL
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
    Default: "50_VPCPeeringCrossAccount"
  BucketObject:
    Description: File in the bucket that contain parameters
    Type: String
    Default: "50_VPCPrivateConnectivityVPCPeering.json"
  Phase:
    Description: "Deploy successively Phase1 and Phase2 and alternate between th two Accounts"
    Type: String
    Default: Phase1
    AllowedValues:
      - Phase1
      - Phase2
  FirstAccountId:
    Description: First AWS Account ID for VPC peering
    Type: String
  FirstRegion:
    Description: Region of the first AWS Account for VPC peering
    Type: String
    Default: eu-west-3
  SecondAccountId:
    Description: Second AWS Account ID for VPC peering
    Type: String
  SecondRegion:
    Description: Region of the second AWS Account for VPC peering
    Type: String
    Default: eu-central-1
  
  InternetGatewayName:
    Type: String
    Default: "VPC-IGW"

Mappings:
  RegionMap:
    eu-west-3:    
      PeerRegion: eu-central-1
      VPCName: "A-VPC"
      VPCCidrBlock: 10.10.0.0/16
      VPCPeeringConnectionName: "A-VPCPeering"
      SubnetName: "A-PublicSubnet"
      SubnetCidrBlock: 10.10.0.0/24
      SubnetPublic: True
      DefaultRouteTableName: "A-VPC-Default-RT"      
      SubnetRouteTableName: "A-Subnet-RT"
      InstanceName: "A-Instance"
      InstanceImageId: ami-015875403620174eb
      KeyName: "dso-paris"
      InstanceSGCidr: 0.0.0.0/0
    eu-central-1:
      PeerRegion: eu-west-3
      VPCName: "B-VPC"
      VPCCidrBlock: 10.20.0.0/16
      VPCPeeringConnectionName: "B-VPCPeering"
      SubnetName: "B-PrivateSubnet"
      SubnetCidrBlock: 10.20.0.0/24
      SubnetPublic: False
      DefaultRouteTableName: "B-VPC-Default-RT"      
      SubnetRouteTableName: "B-Subnet-RT"
      InstanceName: "B-Instance"
      InstanceImageId: ami-00060fac2f8c42d30
      KeyName: "dso-francfort"
      InstanceSGCidr: 10.10.0.0/16

Conditions:
  IsFirstAccount: !Equals [!Ref "AWS::Region", !Ref FirstRegion]
  IsSecondAccount: !Equals [!Ref "AWS::Region", !Ref SecondRegion]
  IsPhaseSecondPhase:  !Equals [ "Phase2", !Ref Phase] 

Resources:
  Lambdas:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_Lambda.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey

  VPCAndSubnets:
    Type: AWS::CloudFormation::Stack
    DependsOn: Lambdas
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_VPCAndSubnets.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        VPCName: !FindInMap [RegionMap, !Ref "AWS::Region", VPCName]
        VPCCidrBlock: !FindInMap [RegionMap, !Ref "AWS::Region", VPCCidrBlock]
        SubnetName: !FindInMap [RegionMap, !Ref "AWS::Region", SubnetName]
        SubnetCidrBlock: !FindInMap [RegionMap, !Ref "AWS::Region", SubnetCidrBlock]
        SubnetPublic: !FindInMap [RegionMap, !Ref "AWS::Region", SubnetPublic]

  # Create a role for remote account to create VPC Peering
  PeerRole:
    Type: AWS::CloudFormation::Stack
    Condition: IsFirstAccount
    DependsOn: Lambdas
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_PeerRole.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        FirstAccountId: !Ref FirstAccountId
        PeerRequesterAccountId: !Ref SecondAccountId        
        
  # Make VPC peering with the first account
  VPCPeering:
    Type: AWS::CloudFormation::Stack
    Condition: IsSecondAccount
    DependsOn: Lambdas
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_VPCPeering.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        PeerAccountId: !Ref FirstAccountId
        PeerRegion: !Ref FirstRegion

  # Create Internet Gateway and default route table for public subnet
  InternetGateway:
    Type: AWS::CloudFormation::Stack
    Condition: IsFirstAccount
    DependsOn: Lambdas
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_InternetGateway.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        InternetGatewayName:  !Ref InternetGatewayName
 
  # Create Route Tables and Routes between subnets
  SubnetRouteTables:
    Type: AWS::CloudFormation::Stack
    Condition: IsPhaseSecondPhase
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_SubnetRouteTables.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        SubnetPublic: !FindInMap [RegionMap, !Ref "AWS::Region", SubnetPublic]
        DefaultRouteTableName: !FindInMap [RegionMap, !Ref "AWS::Region", DefaultRouteTableName]
        SubnetRouteTableName: !FindInMap [RegionMap, !Ref "AWS::Region", SubnetRouteTableName]
        DestinationCidrBlock: !FindInMap [RegionMap, !FindInMap [RegionMap, !Ref "AWS::Region", PeerRegion], VPCCidrBlock]

  Instances:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn: Lambdas
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/50_Instances.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        VPCId: !GetAtt VPCAndSubnets.Outputs.VpcId
        SubnetId: !If [IsFirstAccount, !GetAtt VPCAndSubnets.Outputs.PublicSubnetId, !GetAtt VPCAndSubnets.Outputs.PrivateSubnetId]
        InstanceName: !FindInMap [RegionMap, !Ref "AWS::Region", InstanceName]
        InstanceImageId: !FindInMap [RegionMap, !Ref "AWS::Region", InstanceImageId]
        KeyName: !FindInMap [RegionMap, !Ref "AWS::Region", KeyName]
        InstanceSGCidr: !FindInMap [RegionMap, !Ref "AWS::Region",InstanceSGCidr]
        