---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a role for remote account to create VPC Peering

Parameters:
  Bucket:
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: Key to find object in the bucket
    Type: String

Resources:
  PrivateInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: Private-Instance-Role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Path: /

  PrivateInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: Private-Instance-Profile
      Path: /
      Roles: 
       - !Ref PrivateInstanceRole

  InstanceS3Policy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: S3-Allow-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          -
            Effect: Allow
            Action:
              - s3:Get*
              - s3:Put*
              - s3:List*
              - s3:AbortMultipartUpload 
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/${BucketKey}/*"
              - !Sub "arn:aws:s3:::${Bucket}/${BucketKey}"
      Roles:
        -
          !Ref PrivateInstanceRole


Outputs:
  PrivateInstanceRoleId:
    Description: ID of the Private Instance Role
    Value: !Ref PrivateInstanceRole
  PrivateInstanceProfileId:
    Description: ID of the Private Instance Profile
    Value: !Ref PrivateInstanceProfile
  InstanceS3PolicyId:
    Description: ID of the Instance S3 Policy
    Value: !Ref InstanceS3Policy
