---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create CustomerGateway

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: "CloudFormation bucket URL"
    Type: String    
  BucketKey:
    Default: "data.json"
    Description: File name to save parameters in the bucket
    Type: String
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues:
      - "false"
      - "true"
    Default: "false"
    Description: "Backup values in file specified by Bucket and BucketKey"
    Type: String

  # Stack parameters
  BgpAsn:
    Default: 65500
    Description: "For customer gateway devices that support BGP, specify the device's ASN"
    Type: String
  Name:
    Default: "Default"
    Description: "Customer Gateway name"
    Type: String
  IpAddress:
    Description: "IPv4 address for the customer gateway device's outside interface"
    Type: String
  Type:
    Default: ipsec.1
    Description: "Customer Gateway type"
    Type: String    

Conditions:
  isSavedInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  # Virtual Private Gateway and Attachment
  CustomerGateway:
    Type: AWS::EC2::CustomerGateway
    Properties:
      BgpAsn: !Ref BgpAsn
      IpAddress: !Ref IpAddress
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-${Name}-CGW" 
      Type: !Ref Type

  CustomerGatewayIdBackup:
    Type: AWS::CloudFormation::CustomResource
    Condition: isSavedInS3File
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      Key: !Sub "${AWS::Region}-${ProjectName}-${EnvironmentName}-${Name}-CGWId"
      Value: !Ref CustomerGateway

Outputs:
  CustomerGatewayId:
    Description: "Id of the Customer Gateway"
    Value: !Ref CustomerGateway
