---
AWSTemplateFormatVersion: "2010-09-09"
Description:  "Generic template to deploy Subnets"

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: "CloudFormation bucket URL"
    Type: String    
  BucketKey:
    Default: "data.json"
    Description: File name to save parameters in the bucket
    Type: String
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues:
      - "false"
      - "true"
    Default: "false"
    Description: "Backup values in file specified by Bucket and BucketKey"
    Type: String

  # Stack parameters
  AvailabilityZone:
    Description: "Subnet AZ"
    Type: String
  CidrBlock:
    Description: "Subnet Cidr"
    Type: String
  MapPublicIpOnLaunch:
    Description: "Subnet by default is public"
    Type: String
    AllowedValues:
    - true
    - false
  SubnetName:
    Description: "Subnet name"
    Type: String
  VpcId:
    Description: "ID of the VPC"
    Type: String

Conditions:
  isSavedInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref CidrBlock
      MapPublicIpOnLaunch: !Ref MapPublicIpOnLaunch
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub "${ProjectName}-${EnvironmentName}-${SubnetName}"

  SubnetIdBackup:
    Type: AWS::CloudFormation::CustomResource
    Condition: isSavedInS3File
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      Key: !Sub "${AWS::Region}-${ProjectName}-${EnvironmentName}-${SubnetName}-SubnetId"
      Value: !Ref Subnet

  SubnetCidrBackup:
    Type: AWS::CloudFormation::CustomResource
    Condition: isSavedInS3File
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      Key: !Sub "${AWS::Region}-${ProjectName}-${EnvironmentName}-${SubnetName}-SubnetCidr"
      Value: !GetAtt Subnet.CidrBlock

Outputs:
  SubnetId:
    Description: "Id of the Subnet"
    Value: !Ref Subnet
  CidrBlock:
    Description: "CidrBlock of the Subnet"
    Value: !GetAtt Subnet.CidrBlock
