---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Internet Gateway and Attachement

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: ""
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: [ "dev", "test", "prod" ]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  Name:
    Default: "Default"
    Description: "Route Table name"
    Type: String
  TgwName:
    Default: "Default"
    Description: "Transit Gateway name"
    Type: String
  TransitGatewayAttachmentId:
    Description: "Transit Gateway Attachment ID"
    Type: String
  TransitGatewayId:
    Description: "Transit Gateway ID"
    Type: String

Conditions:
  saveInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  # Transit Gateway Route Tables
  TransitGatewayRouteTable:
    Type: AWS::EC2::TransitGatewayRouteTable
    Properties:
      Tags:
        - Key: EnvironmentName
          Value: !Ref EnvironmentName
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-${TgwName}-${Name}-TGWRT"
        - Key: ProjectName
          Value: !Ref ProjectName
      TransitGatewayId: !Ref TransitGatewayId
  
  TransitGatewayRouteTableToS3:
    Type: AWS::CloudFormation::CustomResource
    Condition: saveInS3File
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !Join [ ":", [ "arn:aws:lambda", !Sub "${AWS::Region}", !Sub "${AWS::AccountId}", "function:EC2ResourceToS3"]]
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      BucketObject: !Ref BucketObject
      Region: !Ref AWS::Region
      ResourceType: "TransitGatewayRouteTable"
      Key: !Sub "${AWS::Region}:${ProjectName}:${EnvironmentName}:EC2:TransitGatewayRouteTable:${Name}"
      Value: !Ref TransitGatewayRouteTable

  # Transit Gateway Route Table Associations
  TransitGatewayRouteTableAssociation:
    Type: AWS::EC2::TransitGatewayRouteTableAssociation
    Properties:
      TransitGatewayAttachmentId: !Ref TransitGatewayAttachmentId
      TransitGatewayRouteTableId: !Ref TransitGatewayRouteTable

  TransitGatewayRouteTableAssociationIdToS3:
    Type: AWS::CloudFormation::CustomResource
    Condition: saveInS3File
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !Join [ ":", [ "arn:aws:lambda", !Sub "${AWS::Region}", !Sub "${AWS::AccountId}", "function:UpdateParametersFromS3"]]
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      BucketObject: !Ref BucketObject
      Key: !Sub "${AWS::Region}:${ProjectName}:${EnvironmentName}:EC2:TransitGatewayRouteTableAssociation:${Name}:Id"
      Value: !Ref TransitGatewayRouteTableAssociation

Outputs:
  TransitGatewayRouteTableAssociationId:
    Description: "Transit Gateway Route Table Association ID"
    Value: !Ref TransitGatewayRouteTableAssociation
  TransitGatewayRouteTableId:
    Description: "Transit Gateway Route Table ID"
    Value: !Ref TransitGatewayRouteTable