---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Internet Gateway and Attachement

Parameters:
    # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: "CloudFormation bucket URL"
    Type: String    
  BucketKey:
    Default: "data.json"
    Description: File name to save parameters in the bucket
    Type: String
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues:
      - "false"
      - "true"
    Default: "false"
    Description: "Backup values in file specified by Bucket and BucketKey"
    Type: String

  # Stack parameters
  Name:
    Default: "Default"
    Description: "Virtual Private Gateway name"
    Type: String
  Type:
    Default: ipsec.1
    Description: "Virtual Private Gateway type"
    Type: String    
  VpcId:
    Description: "Virtual Private Gateway VPC ID"
    Type: String

Conditions:
  isSavedInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  # Virtual Private Gateway and Attachment
  VirtualPrivateGateway:
    Type: AWS::EC2::VPNGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-${Name}-VPNGW" 
      Type: !Ref Type

  VirtualPrivateGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VpcId
      VpnGatewayId: !Ref VirtualPrivateGateway

  VirtualPrivateGatewayIdBackup:
    Type: AWS::CloudFormation::CustomResource
    Condition: isSavedInS3File
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      Key: !Sub "${AWS::Region}-${ProjectName}-${EnvironmentName}-${Name}-VPGId"
      Value: !Ref VirtualPrivateGateway

  VirtualPrivateGatewayAttachmentIdBackup:
    Type: AWS::CloudFormation::CustomResource
    Condition: isSavedInS3File
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      Key: !Sub "${AWS::Region}-${ProjectName}-${EnvironmentName}-${Name}-VPGAId"
      Value: !Ref VirtualPrivateGatewayAttachment

Outputs:
  VirtualPrivateGatewayId:
    Description: "Id of the Virtual Private Gateway"
    Value: !Ref VirtualPrivateGateway
  VirtualPrivateGatewayAttachmentId:
    Description: "Id of the Virtual Private Gateway Attachment"
    Value: !Ref VirtualPrivateGatewayAttachment