---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template VPC Endpoint Service for NLB or GLB

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: "CloudFormation bucket URL"
    Type: String    
  BucketKey:
    Default: "data.json"
    Description: File name to save parameters in the bucket
    Type: String
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues:
      - "false"
      - "true"
    Default: "false"
    Description: "Backup values in file specified by Bucket and BucketKey"
    Type: String

  # Stack parameters
  ServiceName:
    Description: "The name of the endpoint service."
    Type: String
  SecurityGroupId:
    Description: "The Security Group for VPC Endpoint."
    Type: String
  SubnetId:
    Type: String
  VpcId:
    Type: String
  VpcEndpointType:
    Description: "The type of endpoint."
    Type: String
    Default: "Gateway"
    AllowedValues:
      - "Interface"
      - "Gateway"
      - "GatewayLoadBalancer"

Conditions:
  isSavedInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: false
      SecurityGroupIds:
        - !Ref SecurityGroupId
      ServiceName: !Ref ServiceName
      SubnetIds: 
        - !Ref SubnetId
      VpcEndpointType: !Ref VpcEndpointType
      VpcId: !Ref VpcId

  VpcEndpointIdBackup:
    Type: AWS::CloudFormation::CustomResource
    Condition: isSavedInS3File
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      Key: !Sub "${AWS::Region}-${ProjectName}-${EnvironmentName}-${VpcEndpointType}-VpcEndpointId"
      Value: !Ref VpcEndpoint

Outputs:
  VpcEndpointId:
    Description: "Returns the ID of the VPC endpoint."
    Value: !Ref VpcEndpoint