---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Tables and Route Tables

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "112_VpnSplitTunnel"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  BucketRegion:
    AllowedValues: ["eu-west-3", "eu-central-1"]
    Default: "eu-west-3"
    Description: "Region where is the Bucket"
    Type: String
  EnvironmentName:
    AllowedValues: ["dev", "staging", "test", "prod"]
    ConstraintDescription: "Must specify dev, staging, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: ["false", "true"]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String
  
  # Stack parameters
  InternetGatewayId:
    Description: "Internet Gateway ID"
    Type: String
  NatGatewayId:
    Description: "NAT Gateway ID"
    Type: String

  # Principal network
  PrincipalPublicSubnetId:
    Description: "Public Subnets ID for Principal VPC"
    Type: String
  PrincipalPublicSubnetRouteTableName:
    Description: "Public Subnet Route Tables name for Principal VPC"
    Type: String
  PrincipalSecureSubnetId:
    Description: "Secure Subnets ID for Principal VPC"
    Type: String
  PrincipalSecureSubnetRouteTableName:
    Description: "Secure Subnet Route Tables name for Principal VPC"
    Type: String
  PrincipalPrivateSubnetIds:
    Description: "Private Subnets ID for Principal VPC"
    Type: CommaDelimitedList
  PrincipalPrivateSubnetRouteTableNames:
    Description: "Private Subnet Route Table name for Principal VPC"
    Type: CommaDelimitedList
  PrincipalVpcId:
    Description: "Principal VPC ID"
    Type: String

Resources:
  # Route, Route Table and Associations
  PrincipalPublicSubnetRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Ref PrincipalPublicSubnetRouteTableName
        SubnetId: !Ref PrincipalPublicSubnetId
        VpcId: !Ref PrincipalVpcId

  PrincipalPublicSubnetRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: "0.0.0.0/0"
        RouteTableId: !GetAtt PrincipalPublicSubnetRouteTableStack.Outputs.RouteTableId
        RouteTableName: !Ref PrincipalPublicSubnetRouteTableName
        TargetType: "InternetGateway"
        TargetId: !Ref InternetGatewayId

  PrincipalSecureSubnetRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Ref PrincipalSecureSubnetRouteTableName
        SubnetId: !Ref PrincipalSecureSubnetId
        VpcId: !Ref PrincipalVpcId

  PrincipalSecureSubnetRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: "0.0.0.0/0"
        RouteTableId: !GetAtt PrincipalSecureSubnetRouteTableStack.Outputs.RouteTableId
        RouteTableName: PrincipalSecureSubnetRouteTableName
        TargetType: "NatGateway"
        TargetId: !Ref NatGatewayId

  PrincipalPrivateSubnetRouteTableAStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Select [0, !Ref PrincipalPrivateSubnetRouteTableNames]
        SubnetId: !Select [0, !Ref PrincipalPrivateSubnetIds]
        VpcId: !Ref PrincipalVpcId

  PrincipalPrivateSubnetRouteAStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: "0.0.0.0/0"
        RouteTableId: !GetAtt PrincipalPrivateSubnetRouteTableAStack.Outputs.RouteTableId
        RouteTableName: !Select [0, !Ref PrincipalPrivateSubnetRouteTableNames]
        TargetType: "NatGateway"
        TargetId: !Ref NatGatewayId

  PrincipalPrivateSubnetRouteTableBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Select [1, !Ref PrincipalPrivateSubnetRouteTableNames]
        SubnetId: !Select [1, !Ref PrincipalPrivateSubnetIds]
        VpcId: !Ref PrincipalVpcId

  PrincipalPrivateSubnetRouteBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: "0.0.0.0/0"
        RouteTableId: !GetAtt PrincipalPrivateSubnetRouteTableBStack.Outputs.RouteTableId
        RouteTableName: !Select [1, !Ref PrincipalPrivateSubnetRouteTableNames]
        TargetType: "NatGateway"
        TargetId: !Ref NatGatewayId

Outputs:
  PrincipalPublicSubnetRouteId:
    Description: "Principal Public Subnet Route ID"
    Value: !GetAtt PrincipalPublicSubnetRouteStack.Outputs.RouteId
  PrincipalPublicSubnetRouteTableAssociationId:
    Description: "Principal Public Route Table Association ID"
    Value: !GetAtt PrincipalPublicSubnetRouteTableStack.Outputs.SubnetRouteTableAssociationId
  PrincipalPublicSubnetRouteTableId:
    Description: "Principal Public Subnet Route Table ID"
    Value: !GetAtt PrincipalPublicSubnetRouteTableStack.Outputs.RouteTableId

  PrincipalSecureSubnetRouteId:
    Description: "Principal Secure Subnet Route ID"
    Value: !GetAtt PrincipalSecureSubnetRouteStack.Outputs.RouteId
  PrincipalSecureSubnetRouteTableAssociationId:
    Description: "Principal Secure Route Table Association ID"
    Value: !GetAtt PrincipalSecureSubnetRouteTableStack.Outputs.SubnetRouteTableAssociationId
  PrincipalSecureSubnetRouteTableId:
    Description: "Principal Secure Subnet Route Table ID"
    Value: !GetAtt PrincipalSecureSubnetRouteTableStack.Outputs.RouteTableId

  PrincipalPrivateSubnetRouteIds:
    Description: "Principal Private Subnet Route ID"
    Value: !Join
      - ","
      - - !GetAtt PrincipalPrivateSubnetRouteAStack.Outputs.RouteId
        - !GetAtt PrincipalPrivateSubnetRouteBStack.Outputs.RouteId
  PrincipalPrivateSubnetRouteTableAssociationIds:
    Description: "Principal Private Route Table Association ID"
    Value: !Join
      - ","
      - - !GetAtt PrincipalPrivateSubnetRouteTableAStack.Outputs.SubnetRouteTableAssociationId
        - !GetAtt PrincipalPrivateSubnetRouteTableBStack.Outputs.SubnetRouteTableAssociationId  
  PrincipalPrivateSubnetRouteTableIds:
    Description: "Principal Private Subnet Route Table ID"
    Value: !Join
      - ","
      - - !GetAtt PrincipalPrivateSubnetRouteTableAStack.Outputs.RouteTableId
        - !GetAtt PrincipalPrivateSubnetRouteTableBStack.Outputs.RouteTableId