---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploy Roles

Parameters:
  # Global parameters
  Bucket:
    Description: "CloudFormation bucket URL"
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: "Key to find object in the bucket"
    Type: String
    Default: "113_VpcPeeringConnectionOverClientVpn"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  BucketRegion:
    AllowedValues: ["eu-west-3", "eu-central-1"]
    Default: "eu-west-3"
    Description: "Region where is the Bucket"
    Type: String
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Account parameters
  PeerRequesterAccountId:
    Description: Second AWS Account ID for VPC peering
    Type: String

  # Instances parameters
  BastionInstanceName:
    Default: "bastion"
    Description: "Bastion Instances name"
    Type: String
  ApplicationInstanceName:
    Default: "application"
    Description: "Application Instances name"
    Type: String
  CaServerInstanceName:
    Default: "ca-server"
    Description: "CA Server Instances name"
    Type: String

Resources:
  VpcPeeringCrossAccountRoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/IAM/AcceptVpcPeeringConnectionRole.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File 
        PeerRequesterAccountId: !Ref PeerRequesterAccountId

  BastionRoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/IAM/InstanceRole.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        InstanceProfileName: !Sub "${BastionInstanceName}-Instance-Profile"
        RoleName: !Sub "${BastionInstanceName}-Instance-Role"
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File

  ApplicationRoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/IAM/InstanceRole.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        InstanceProfileName: !Sub "${ApplicationInstanceName}-Instance-Profile"
        RoleName: !Sub "${ApplicationInstanceName}-Instance-Role"
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File

  CaServerRoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/IAM/InstanceCaServerRole.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        InstanceProfileName: !Sub "${CaServerInstanceName}-Instance-Profile"
        RoleName: !Sub "${CaServerInstanceName}-Instance-Role"
        SaveInS3File: !Ref SaveInS3File

Outputs:
  VpcPeeringCrossAccountRoleArn:
    Description: "VPC peering cross Account Role ARN"
    Value: !GetAtt VpcPeeringCrossAccountRoleStack.Outputs.RoleArn
  VpcPeeringCrossAccountRoleId:
    Description: "VPC peering cross Account Role ID"
    Value: !GetAtt VpcPeeringCrossAccountRoleStack.Outputs.RoleId

  BastionRoleArn:
    Description: "Bastion Role ARN"
    Value: !GetAtt BastionRoleStack.Outputs.RoleArn
  BastionRoleId:
    Description: "Bastion Role ID"
    Value: !GetAtt BastionRoleStack.Outputs.RoleId
  BastionInstanceProfileArn:
    Description: "Bastion Instance Profile ARN"
    Value: !GetAtt BastionRoleStack.Outputs.InstanceProfileArn
  BastionInstanceProfileId:
    Description: "Bastion Instance Profile ID"
    Value: !GetAtt BastionRoleStack.Outputs.InstanceProfileId

  ApplicationRoleArn:
    Description: "Application Role ARN"
    Value: !GetAtt ApplicationRoleStack.Outputs.RoleArn
  ApplicationRoleId:
    Description: "Application Role ID"
    Value: !GetAtt ApplicationRoleStack.Outputs.RoleId
  ApplicationInstanceProfileArn:
    Description: "Application Instance Profile ARN"
    Value: !GetAtt ApplicationRoleStack.Outputs.InstanceProfileArn
  ApplicationInstanceProfileId:
    Description: "Application Instance Profile ID"
    Value: !GetAtt ApplicationRoleStack.Outputs.InstanceProfileId

  CaServerRoleArn:
    Description: "Instance CA Server Role ARN"
    Value: !GetAtt CaServerRoleStack.Outputs.RoleArn
  CaServerRoleId:
    Description: "Instance CA Server Role ID"
    Value: !GetAtt CaServerRoleStack.Outputs.RoleId
  CaServerInstanceProfileArn:
    Description: "Instance CA Server Profile ARN"
    Value: !GetAtt CaServerRoleStack.Outputs.InstanceProfileArn
  CaServerInstanceProfileId:
    Description: "Instance CA Server Profile ID"
    Value: !GetAtt CaServerRoleStack.Outputs.InstanceProfileId