---
AWSTemplateFormatVersion: "2010-09-09"
Description:  "Generic template to deploy HostedZone"

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: ""
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: [ "dev", "test", "prod" ]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  Comment:
    Description: >-
      Optional: The comment of the hosted zone.
    MaxLength: 256
    Type: String
  Name:
    Description: >-
      Optional: The name of the domain. This should be a fully qualified
      domain, such as www.example.com. The trailing dot is not required.
    Type: String
    MaxLength: 1024
  TagKeys: # Required: Yes
    Default: ""
    Description: >-
      Optional: The list of values of the keys of tags that you want to
      associate with the hosted zone.
    Type: CommaDelimitedList
  TagValues:
    Default: ""
    Description: >-
      Optional: The list of values of the Value element for each tag that you
      want to associate with the hosted zone.
    Type: CommaDelimitedList
  VpcIds:
    Default: ""
    Description: >-
      Optional: The list of VPCs that you want to associate with this hosted
      zone. Note that the VPCs and the hosted zone must already be associated
      or disassociated for the update to succeed.
    Type: CommaDelimitedList
  VpcRegions:
    Default: ""
    Description: >-
      Optional: Private hosted zones: A complex type that contains information
      about the VPCs that are associated with the specified hosted zone.
    Type: CommaDelimitedList

Conditions:
  asNoTagKeys: !Equals [ !Select [0, !Ref TagKeys], ""]
  isPublicHostedZone: !Equals [ !Select [0, !Ref VpcIds], ""]
  saveInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: !Ref Comment
      HostedZoneTags: !If
        - asNoTagKeys
        - !Ref AWS::NoValue
        - - Key: !Select [0, !Ref TagKeys]
            Value: !Select [0, !Ref TagValues]
      Name: !Ref Name
      VPCs: !If
        - isPublicHostedZone
        - !Ref AWS::NoValue
        - - VPCId: !Select [0, !Ref VpcIds]
            VPCRegion: !Select [0, !Ref VpcRegions]

  HostedZoneToS3:
    Type: AWS::CloudFormation::CustomResource
    Condition: saveInS3File
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !Join [ ":", [ "arn:aws:lambda", !Sub "${AWS::Region}", !Sub "${AWS::AccountId}", "function:Route53ResourceToS3"]]
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      BucketObject: !Ref BucketObject
      Region: !Ref AWS::Region
      ResourceType: "HostedZone"
      Key: !Sub "${AWS::Region}:${ProjectName}:${EnvironmentName}:Route53:HostedZone:${Name}"
      Value: !Ref HostedZone

Outputs:
  HostedZoneId:
    Description: "Id of the HostedZone"
    Value: !Ref HostedZone