---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a S3 Gateway Endpoint

Parameters:
  Bucket:
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
  VPCId:
    Type: String
  PrivateRouteTableId:
    Type: String

Resources:  
  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:Put*
              - s3:List*
              - s3:AbortMultipartUpload 
            Principal: '*'
            Resource:
              - !Sub "arn:aws:s3:::${Bucket}/${BucketKey}/*"
              - !Sub "arn:aws:s3:::${Bucket}/${BucketKey}"
      RouteTableIds: 
        - !Ref PrivateRouteTableId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      VpcId: !Ref VPCId


Outputs:
  GatewayEndpointId:
    Description: "Id of the S3 Gateway Endpoint"
    Value: !Ref S3GatewayEndpoint  