---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys a VPC, Public and Private network

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "25_EgressOnlyInternetGatewayForIpV6"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: ["dev", "test", "staging", "prod"]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String
  
  # Stack parameters
  EnableIpv6:
    AllowedValues: [ "false", "true" ]
    Default: "true"
    Description: "If true, the VPC will support IPv6"
    Type: String
  SubnetName:
    Default: "Subnet"
    Description: Subnet name
    Type: String
  SubnetPrivateCidrBlock:
    Default: 10.10.1.0/24
    Description: "Private Subnet CIDR"
    Type: String
  SubnetPublicCidrBlock:
    Default: 10.10.0.0/24
    Description: "Public Subnet CIDR"
    Type: String
  VpcName:
    Default: "MyVPC"
    Description: VPC name
    Type: String
  VpcCidrBlock:
    Default: 10.10.0.0/16
    Description: "The IPv4 network range for the VPC, in CIDR notation."
    Type: String

Conditions:
  SaveInS3File: !Equals [ !Ref SaveInS3File, "true"]

Resources:
  # VPC, DHCPOptions, Association and App and DB Subnets
  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Vpc.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        CidrBlock: !Ref VpcCidrBlock
        EnableDnsSupport: "true"
        EnableDnsHostnames: "true"
        EnableIpv6: !Ref EnableIpv6
        InstanceTenancy: default
        VpcName: !Ref VpcName

  SubnetPrivateStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [ 0, !GetAZs ]
        CidrBlock: !Ref   SubnetPrivateCidrBlock
        EnableIpv6: !Ref EnableIpv6
        MapPublicIpOnLaunch: "false"
        Ipv6CidrBlock: !Select [0, !Cidr [ !GetAtt VpcStack.Outputs.VpcIpv6CidrBlock, 256, 64 ] ]
        SubnetName: !Sub "${SubnetName}-Private"
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  SubnetPublicStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [ 0, !GetAZs ]
        CidrBlock: !Ref SubnetPublicCidrBlock
        MapPublicIpOnLaunch: "true"
        SubnetName: !Sub "${SubnetName}-Public"
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  VpcToS3:
    Type: AWS::CloudFormation::CustomResource
    Condition: SaveInS3File
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      ServiceToken: !Join [ ":", [ "arn:aws:lambda", !Sub "${AWS::Region}", !Sub "${AWS::AccountId}", "function:EC2ResourceToS3"]]
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Ref BucketKey
      BucketObject: !Ref BucketObject
      Region: !Ref AWS::Region
      ResourceType: "Vpc"
      Key: !Sub "${AWS::Region}:${ProjectName}:${EnvironmentName}:EC2:VPC:${VpcName}"
      Value: !GetAtt VpcStack.Outputs.VpcId

Outputs:
  VpcId:
    Description: "VPC Id"
    Value: !GetAtt VpcStack.Outputs.VpcId
  VpcCidrBlock:
    Description: The primary IPv4 CIDR block for the VPC. 
    Value: !GetAtt VpcStack.Outputs.VpcCidrBlock
  VpcIpv6CidrBlock:
    Description: The IPv6 CIDR blocks for the VPC.
    Value: !GetAtt VpcStack.Outputs.VpcIpv6CidrBlock

  SubnetPrivateId:
    Description: "Private Subnet Id"
    Value: !GetAtt SubnetPrivateStack.Outputs.SubnetId
  SubnetCidrBlock:
    Description: The IPv4 CIDR blocks that are associated with the subnet.
    Value: !GetAtt SubnetPrivateStack.Outputs.SubnetCidrBlock
  SubnetIpV6CidrBlock:
    Description: The IPv6 CIDR blocks that are associated with the subnet.
    Value: !GetAtt SubnetPrivateStack.Outputs.SubnetIpV6CidrBlock

  SubnetPublicId:
    Description: "Public Subnets Id"
    Value: !GetAtt SubnetPublicStack.Outputs.SubnetId
  SubnetPublicCidrBlock:
    Description: The IPv4 CIDR blocks that are associated with the subnet.
    Value: !GetAtt SubnetPublicStack.Outputs.SubnetCidrBlock
  SubnetPublicIpV6CidrBlock:
    Description: The IPv6 CIDR blocks that are associated with the subnet.
    Value: !GetAtt SubnetPublicStack.Outputs.SubnetIpV6CidrBlock
