---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys a VPC, and Subnets

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  EnvironmentName:
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  
# Stack parameters
  AvailabilityZone:
    Description: "The AZ of the subnets"
    Type: String
  CreatePublicSubnet:
    AllowedValues:
      - "false"
      - "true"      
    Default: "false"
    Description: "The AZ of the subnets"
    Type: String
  VpcName:
    Description: "VPC name"
    Type: String
  VpcCidrBlock:
    Description: "The IPv4 network range for the VPC, in CIDR notation."
    Type: String

Conditions:
  createPublicSubnet: !Equals [ !Ref CreatePublicSubnet, "true"]

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Vpc.yaml"
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        CidrBlock: !Ref VpcCidrBlock
        VpcName: !Ref VpcName

  PublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    Condition: createPublicSubnet
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        AvailabilityZone: !Ref AvailabilityZone
        CidrBlock:
          !Select 
            - 0
            - Fn::Cidr: [ !Ref VpcCidrBlock, 2, 8] 
        MapPublicIpOnLaunch: true
        SubnetName: !Sub "${EnvironmentName}-${ProjectName}-${VpcName}-PublicSubnet"
        VpcId: !GetAtt VpcStack.Outputs.VpcId
        
  PrivateSubnetStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        AvailabilityZone: !Ref AvailabilityZone
        CidrBlock:
          !Select 
            - 1
            - Fn::Cidr: [ !Ref VpcCidrBlock, 2, 8] 
        MapPublicIpOnLaunch: false
        SubnetName: !Sub "${EnvironmentName}-${ProjectName}-${VpcName}-PrivateSubnet"
        VpcId: !GetAtt VpcStack.Outputs.VpcId

Outputs:
  VpcId:
    Description: "Id of the VPC"
    Value: !GetAtt VpcStack.Outputs.VpcId
  PublicSubnetId:
    Description: "Id of the Public Subnet"
    Value: !If [ createPublicSubnet, !GetAtt PublicSubnetStack.Outputs.SubnetId, "" ]
  FirstCidr:
    Description: "Cidr of the Public Subnet"
    Value: !If [ createPublicSubnet, !GetAtt PublicSubnetStack.Outputs.CidrBlock, "" ]
  PrivateSubnetId:
    Description: "Id of the Private Subnet"
    Value: !GetAtt PrivateSubnetStack.Outputs.SubnetId
  SecondCidr:
    Description: "Cidr of the Private Subnet"
    Value: !GetAtt PrivateSubnetStack.Outputs.CidrBlock
