---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Tables and Route Tables

Parameters:
  # Global parameters
  Bucket:
    Description: CloudFormation buket URL
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
    Default: "71_TransitGatewayRestrictedRouting"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"

  # Stack parameters
  DestinationCidrBlock:
    Description: "CIDR range of VPC"
    Type: String
  InternetGatewayId:
    Description: "Internet Gateway ID"
    Type: String
  RouteTableNames:
    Description: "Names of all Route Tables"
    Type: String
  SubnetPrivateIds:
    Description: "Private Subnets IDs"
    Type: String
  SubnetPublicId:
    Description: "Public Subnets ID"
    Type: String
  TransitGatewayId:
    Description: "Transit Gateway ID"
    Type: String
  VpcIds:
    Description: "VPC IDs"
    Type: String

Resources:  
  SubnetAPublicRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCId: !Select [ 0, !Split [ ",", !Ref VpcIds ] ]
        RouteTableName: !Join [ "-", [ !Select [ 0, !Split [ ",", !Ref RouteTableNames ] ], "Public" ] ]
        SaveInS3File: "true"
        SubnetId: !Ref SubnetPublicId

  SubnetAPublicRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        RouteTableId: !GetAtt SubnetAPublicRouteTableStack.Outputs.RouteTableId
        DestinationCidrBlock: "0.0.0.0/0"
        Destinationtype: "InternetGateway"
        GatewayId: !Ref InternetGatewayId
        SaveInS3File: "true"

  SubnetAPrivateRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCId: !Select [ 0, !Split [ ",", !Ref VpcIds ] ]
        RouteTableName: !Join [ "-", [ !Select [ 0, !Split [ ",", !Ref RouteTableNames ] ], "Private" ] ]
        SaveInS3File: "true"
        SubnetId: !Select [ 0, !Split [ ",", !Ref SubnetPrivateIds ] ]

  SubnetAPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        RouteTableId: !GetAtt SubnetAPrivateRouteTableStack.Outputs.RouteTableId
        DestinationCidrBlock: !Ref DestinationCidrBlock
        Destinationtype: "TransitGateway"
        SaveInS3File: "true"
        TransitGatewayId: !Ref TransitGatewayId

  SubnetBPrivateRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCId: !Select [ 1, !Split [ ",", !Ref VpcIds ] ]
        RouteTableName: !Join [ "-", [ !Select [ 1, !Split [ ",", !Ref RouteTableNames ] ], "Private" ] ]
        SaveInS3File: "true"
        SubnetId: !Select [ 1, !Split [ ",", !Ref SubnetPrivateIds ] ]

  SubnetBPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        RouteTableId: !GetAtt SubnetBPrivateRouteTableStack.Outputs.RouteTableId
        DestinationCidrBlock: !Ref DestinationCidrBlock
        Destinationtype: "TransitGateway"
        SaveInS3File: "true"
        TransitGatewayId: !Ref TransitGatewayId

  SubnetCPrivateRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        VPCId: !Select [ 2, !Split [ ",", !Ref VpcIds ] ]
        RouteTableName: !Join [ "-", [ !Select [ 2, !Split [ ",", !Ref RouteTableNames ] ], "Private" ] ]
        SaveInS3File: "true"
        SubnetId: !Select [ 2, !Split [ ",", !Ref SubnetPrivateIds ] ]

  SubnetCPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        RouteTableId: !GetAtt SubnetCPrivateRouteTableStack.Outputs.RouteTableId
        DestinationCidrBlock: !Ref DestinationCidrBlock
        Destinationtype: "TransitGateway"
        SaveInS3File: "true"
        TransitGatewayId: !Ref TransitGatewayId

Outputs:
  SubnetPrivateRouteIds:
    Description: "Private Subnet Route IDs"
    Value: !Join
      - ","
      - - !GetAtt SubnetAPrivateRouteStack.Outputs.RouteId
        - !GetAtt SubnetBPrivateRouteStack.Outputs.RouteId
        - !GetAtt SubnetCPrivateRouteStack.Outputs.RouteId

  SubnetPrivateRouteTableAssociationIds:
    Description: "Private Route Table Association IDs"
    Value: !Join
      - ","
      - - !GetAtt SubnetAPrivateRouteTableStack.Outputs.SubnetRouteTableAssociationId
        - !GetAtt SubnetBPrivateRouteTableStack.Outputs.SubnetRouteTableAssociationId
        - !GetAtt SubnetCPrivateRouteTableStack.Outputs.SubnetRouteTableAssociationId

  SubnetPrivateRouteTableIds:
    Description: "Private Subnet Route Table IDs"
    Value: !Join
      - ","
      - - !GetAtt SubnetAPrivateRouteTableStack.Outputs.RouteTableId
        - !GetAtt SubnetBPrivateRouteTableStack.Outputs.RouteTableId
        - !GetAtt SubnetCPrivateRouteTableStack.Outputs.RouteTableId

  SubnetPublicRouteIds:
    Description: "Public Subnet Route IDs"
    Value: !GetAtt SubnetAPublicRouteStack.Outputs.RouteId

  SubnetPublicRouteTableIds:
    Description: "Public Subnet Route Table IDs"
    Value: !GetAtt SubnetAPublicRouteTableStack.Outputs.RouteTableId

  SubnetPublicRouteTableAssociationIds:
    Description: "Public Route Table Association IDs"
    Value: !GetAtt SubnetAPublicRouteTableStack.Outputs.SubnetRouteTableAssociationId