---

AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys a VPC, Public and Private Subnets

Parameters:
  VPCCidrBlock:
    Type: String
  VPCName:
    Type: String
  SubnetCidrBlock:
    Type: String
  SubnetName:
    Type: String
  SubnetPublic:
    Default: false
    Type: String
    AllowedValues:
      - true
      - false

Conditions:
  isPublicSubnet:
    !Equals ["true", !Ref SubnetPublic] 
  isPrivateSubnet:
    !Equals ["false", !Ref SubnetPublic] 

Resources:
  # VPC, DHCPOptions, Association and App and DB Subnets
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCCidrBlock
      EnableDnsSupport: "false"
      EnableDnsHostnames: "false"
      InstanceTenancy: default
      Tags:
        - Key: Name
          Value: !Ref VPCName

  PublicSubnet:
    Type: AWS::EC2::Subnet
    Condition: isPublicSubnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: !Ref SubnetCidrBlock
      MapPublicIpOnLaunch: true
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Ref SubnetName

  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Condition: isPrivateSubnet
    Properties:
      AvailabilityZone: !Select [ 0, !GetAZs ]
      CidrBlock: !Ref SubnetCidrBlock
      MapPublicIpOnLaunch: false
      VpcId: !Ref VPC
      Tags:
      - Key: Name
        Value: !Ref SubnetName

Outputs:
  VpcId:
    Description: Id of the VPC
    Value: !Ref VPC
  PublicSubnetId:
    Condition: isPublicSubnet
    Description: Id of the PublicSubnet
    Value: !Ref PublicSubnet
  PrivateSubnetId:
    Condition: isPrivateSubnet
    Description: Id of the PrivateSubnet
    Value: !Ref PrivateSubnet
