---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a role for remote account to create VPC Peering

Parameters:
  VPCId:
    Type: String
  PeerAccountId:
    Type: String
  PeerRegion:
    Type: String
  PeerRoleArn:
    Type: String
  PeerVPCId:
    Type: String

Resources:
  VPCPeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VPCId
      PeerVpcId: !Ref PeerVPCId
      PeerRegion: !Ref PeerRegion
      PeerOwnerId: !Ref PeerAccountId
      PeerRoleArn: !Ref PeerRoleArn
      Tags:
      - Key: Name
        Value: VPCPeeringConnection

Outputs:
  VPCPeeringConnectionId:
    Value: !Ref VPCPeeringConnection