---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a role for remote account to create VPC Peering

Parameters:
  # Global parameters
  Bucket:
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Description: File in the bucket that contain parameters
    Type: String

  # Stack parameters
  VPCId:
    Type: String
  PeerAccountId:
    Type: String
  PeerRegion:
    Type: String


Resources:
  # Get VPC ID of the other Account and Region
  GetPeerVPCId:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:GetParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: !Sub "${PeerAccountId}:${PeerRegion}:VPCID"
      Delay: 30
      DelayCount: 3

  # Get Role ARN of the other Account and Region
  GetPeerRoleArn:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:GetParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: "PeerRoleArn"
      Delay: 30
      DelayCount: 3

  # Create VPC Peering Connection
  PeeringConnection:
    Type: AWS::EC2::VPCPeeringConnection
    Properties:
      VpcId: !Ref VPCId
      PeerVpcId: !GetAtt GetPeerVPCId.Value
      PeerRegion: !Ref PeerRegion
      PeerOwnerId: !Ref PeerAccountId
      PeerRoleArn: !GetAtt GetPeerRoleArn.Value
      Tags:
      - Key: Name
        Value: VpcPeeringConnection

  # Save VPC Peering Connection ID
  PeeringConnectionBackup:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: "VpcPeeringConnectionId"
      Value: !Ref PeeringConnection

Outputs:
  PeeringConnectionId:
    Description: ID of the VPC Peering Connection
    Value: !Ref  PeeringConnection