---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create a role for remote account to create VPC Peering

Parameters:
  # Global parameters
  Bucket:
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Description: File in the bucket that contain parameters
    Type: String
  
  # Stack parameters
  # Stack parameters
  VPCId:
    Type: String
  SubnetId:
    Type: String
  InstanceName:
    Type: String
  InstanceImageId:
    Type: AWS::EC2::Image::Id
  KeyName:
    Type: String
  InstanceSGCidr:
    Type: String

Resources:     
  # Instances and Security Groups
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone:  !Select [ 0, !GetAZs ]
      ImageId: !Ref InstanceImageId
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        - !Ref SSHSecurityGroup
        - !Ref ICMPSecurityGroup
      SubnetId: !Ref SubnetId
      Tags:
        - Key: Name
          Value: !Ref InstanceName
  
  InstanceBackup:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: !Sub "${AWS::AccountId}:${AWS::Region}:InstanceId"
      Value: !Ref Instance

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
      - CidrIp: !Ref InstanceSGCidr
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: SSH-SG

  SSHSecurityGroupBackup:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: !Sub "${AWS::AccountId}:${AWS::Region}:SSHSecurityGroupId"
      Value: !Ref SSHSecurityGroup

  ICMPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable Ping
      SecurityGroupIngress:
      - CidrIp: !Ref InstanceSGCidr
        FromPort: -1
        IpProtocol: icmp
        ToPort: -1
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: ICMP-SG

  ICMPSecurityGroupBackup:
    Type: AWS::CloudFormation::CustomResource
    Properties:
      ServiceToken: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:UpdateParametersFromS3"
      ServiceTimeout: 60
      Bucket: !Ref Bucket
      BucketKey: !Sub "${BucketKey}/${BucketObject}"
      Key: !Sub "${AWS::AccountId}:${AWS::Region}:ICMPSecurityGroupId"
      Value: !Ref ICMPSecurityGroup

Outputs:
  InstanceId:
    Description: Id of the Instance 
    Value: !Ref Instance
  InstancePrivateIP:
    Description: Private IP v4 of the Instance 
    Value: !GetAtt Instance.PrivateIp
  SSHSecurityGroupId:
    Description: SSH Security Group Id of the instance
    Value: !Ref SSHSecurityGroup
  ICMPSecurityGroupId:
    Description: ICMP Security Group Id of the instance
    Value: !Ref ICMPSecurityGroup