---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template for creating Lambda to read parameters in file from S3

Resources:
  # Event JSON to test Lambda
  # {
  #   "Bucket": "hawkfund-cloudformation",
  #   "BucketKey": "VPCPeeringCrossAccount/VPCPrivateConnectivityVPCPeering.json",
  #   "Key": "VpcPeeringConnectionId",
  #  }
  GetParametersFromS3:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: |
          import boto3
          import cfnresponse
          import json

          client = boto3.client('s3')

          def lambda_handler(event, context):
            responseData  = {}
            bucket =  event["ResourceProperties"]["Bucket"]
            bucketKey = event["ResourceProperties"]["BucketKey"]
            parameterKey = event["ResourceProperties"]["Key"]
            try:
              # Read file from s3
              response = client.get_object(
                  Bucket=bucket,
                  Key=bucketKey
              )
              print(response)
              json_data = response["Body"].read().decode('utf-8')
              data = json.loads(json_data)             
              responseData["Value"] = json.loads(data)[parameterKey]
              cfnresponse.send(event, context, cfnresponse.SUCCESS, responseData)                            
            except Exception as err:
              print("ERROR: No file present on the s3 Bucket")
              responseData['Data'] = str(err)
              cfnresponse.send(event, context, cfnresponse.FAILED, responseData)
      Description: Function to read parameter from JSON file in a S3 bucket
      FunctionName: GetParametersFromS3
      Handler: index.lambda_handler
      MemorySize: 128
      Role: !Join [":", ["arn:aws:iam:", !Sub "${AWS::AccountId}", !Sub "role/GetParametersFromS3" ] ]
      Runtime: python3.9

Outputs:
  GetParametersFromS3Arn:
    Description: "ARN of GetParametersFromS3 Lambda"
    Value: !GetAtt GetParametersFromS3.Arn