---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Internet Gateway and Attachement

Parameters:
  # Global parameters
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"

  # Stack parameters
  VPCId:
    Type: String
  InternetGatewayName:
    Type: String

Resources:  
  # Internet Gateway and Attachment
  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-${InternetGatewayName}-IGW" 

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPCId

Outputs:
  InternetGatewayId:
    Description: "Id of the InternetGateway"
    Value: !Ref InternetGateway
  InternetGatewayAttachmentId:
    Description: "Id of th InternetGatewayAttachment"
    Value: !Ref InternetGatewayAttachment
