---
AWSTemplateFormatVersion: "2110-09-09"
Description:  This template create bastion and application Instances and Security Groups

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "21_NatInstance"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: ["dev", "test", "staging", "prod"]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String
  
  # Stack parameters
  KeyName:
    Default: "dso-paris"
    Description: "Instances Key name"
    Type: String

  # Appplication parameters
  ApplicationInstanceImageId:
    Default: ami-08461dc8cd9e834e0
    Description: "Application Instance AMI"
    Type: AWS::EC2::Image::Id
  ApplicationInstanceName:
    Default: "Application"
    Description: "Application Instances name"
    Type: String
  ApplicationInstanceType:
    Default: t2.micro
    Description: "Application Instances type"
    Type: String
  ApplicationInstanceProfile:
    Description: "Profile of the Application"
    Type: String
  ApplicationInstanceSecurityGroup:
    Description: "Application Security Group"
    Type: String
  ApplicationInstanceSubnetId:
    Description: "Application Subnet ID"
    Type: String

  # Bastion parameters
  BastionInstanceImageId:
    Default: ami-08461dc8cd9e834e0
    Description: "Bastion Instance AMI"
    Type: AWS::EC2::Image::Id
  BastionInstanceName:
    Default: "Bastion"
    Description: "Bastion Instances name"
    Type: String
  BastionInstanceType:
    Default: t2.micro
    Description: "Bastion Instances type"
    Type: String
  BastionInstanceSecurityGroup:
    Description: "Bastion Security Group"
    Type: String
  BastionInstanceSubnetId:
    Description: "Bastion Subnet ID"
    Type: String

  # Nat Instance parameters
  NatInstanceImageId:
    Default: ami-015c7728d5cb3dccd
    Description: "Nat Instance AMI"
    Type: AWS::EC2::Image::Id
  NatInstanceName:
    Default: "Nat Instance"
    Description: "Nat Instances name"
    Type: String
  NatInstanceType:
    Default: t2.micro
    Description: "Nat Instances type"
    Type: String
  NatInstanceSecurityGroup:
    Description: "Nat Security Group"
    Type: String
  NatInstanceSubnetId:
    Description: "Nat Subnet ID"
    Type: String


Resources:
  BastionInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        ElasticIP: "true"
        ImageId: !Ref BastionInstanceImageId
        InstanceName: !Ref BastionInstanceName
        InstanceType: !Ref BastionInstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds: !Ref BastionInstanceSecurityGroup
        SubnetId: !Ref BastionInstanceSubnetId

  ApplicationInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        IamInstanceProfile: !Ref ApplicationInstanceProfile
        ImageId: !Ref ApplicationInstanceImageId
        InstanceName: !Ref ApplicationInstanceName
        InstanceType: !Ref ApplicationInstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds: !Ref ApplicationInstanceSecurityGroup
        SubnetId: !Ref ApplicationInstanceSubnetId

  NatInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        ElasticIP: "false"
        ImageId: !Ref NatInstanceImageId
        InstanceName: !Ref NatInstanceName
        InstanceType: !Ref NatInstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds: !Ref NatInstanceSecurityGroup
        SourceDestCheck: "false"
        SubnetId: !Ref NatInstanceSubnetId

Outputs:
  ApplicationInstanceId:
    Description: "Id of the Application Instance"
    Value: !GetAtt ApplicationInstance.Outputs.InstanceId
  ApplicationInstancePrivateIP:
    Description: "Private IP of the Application Instance"
    Value: !GetAtt ApplicationInstance.Outputs.InstancePrivateIP

  BastionInstanceId:
    Description: "Id of the Bastion Instance"
    Value: !GetAtt BastionInstance.Outputs.InstanceId
  BastionPrivateIP:
    Description: "Private IP of the Bastion Instance"
    Value: !GetAtt BastionInstance.Outputs.InstancePrivateIP
  BastionPublicIP:
    Description: "Public IP of the Bastion Instance"
    Value: !GetAtt BastionInstance.Outputs.InstancePublicIP

  NatInstanceId:
    Description: "Id of the Nat Instance"
    Value: !GetAtt NatInstance.Outputs.InstanceId
  NatPrivateIP:
    Description: "Private IP of the Nat Instance"
    Value: !GetAtt NatInstance.Outputs.InstancePrivateIP
  NatPublicIP:
    Description: "Public IP of the Nat Instance"
    Value: !GetAtt NatInstance.Outputs.InstancePublicIP
