---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template deploys NAT gateways (one in each AZ), and default
  routes for them in the private subnets.

Parameters:
  EnvironmentName:
    Description: "An environment name that is prefixed to resource names"
    Type: String
  ProjectName:
    Description: "A Project name that is prefixed to resource names"
    Type: String

  PublicSubnetId1:
    Description:  A reference to the public subnet in the 1st Availability Zone
    Type: String

  PublicSubnetId2:
    Description:  A reference to the public subnet in the 2nd Availability Zone
    Type: String

  PublicSubnetId3:
    Description:  A reference to the public subnet in the 3rd Availability Zone
    Type: String  

Resources:
  NatGateway1EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway2EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway3EIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  NatGateway1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway1EIP.AllocationId
      SubnetId: !Ref PublicSubnetId1

  NatGateway2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway2EIP.AllocationId
      SubnetId: !Ref PublicSubnetId2

  NatGateway3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt NatGateway3EIP.AllocationId
      SubnetId: !Ref PublicSubnetId3

Outputs:
  NatGatewayId1:
    Description: A reference to the Nat Gateway in the 1st Availability Zone
    Value: !Ref NatGateway1

  NatGatewayId2:
    Description: A reference to the Nat Gateway in the 2nd Availability Zone
    Value: !Ref NatGateway2

  NatGatewayId3:
    Description: A reference to the Nat Gateway in the 3rd Availability Zone
    Value: !Ref NatGateway3
