---
# aws cloudformation validate-template --template-body file://80_security_group.yaml

AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys Security Groups

Parameters:
  ProjectName:
    Description: A Project name that is prefixed to resource names
    Type: String
    Default: "hk"

  EnvironmentName:
    Description: An environment name that is prefixed to resource names
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"

  VpcId:
    Description: ID of the VPC
    Type: String

Resources:
  NoIngressSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: "no-ingress-sg"
      GroupDescription: "Security group with no ingress rule"
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub ${ProjectName}-${EnvironmentName} Security Group (!Ref AvailabilityZone)


Outputs:
  NoIngressSecurityGroup:
    Description: Security group with no ingress rule
    Value: !Ref NoIngressSecurityGroup