---
AWSTemplateFormatVersion: "2010-09-09"
Description:  "Generic template to deploy Subnets"

Parameters:
  # Global parameters
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"

  # Stack parameters
  AvailabilityZone:
    Description: "Subnet AZ"
    Type: String
  CidrBlock:
    Description: "Subnet Cidr"
    Type: String
  MapPublicIpOnLaunch:
    Description: "Subnet by default is public"
    Type: String
    AllowedValues:
    - true
    - false
  SubnetName:
    Description: "Subnet name"
    Type: String
  VpcId:
    Description: "ID of the VPC"
    Type: String

Resources:
  Subnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Ref AvailabilityZone
      CidrBlock: !Ref CidrBlock
      MapPublicIpOnLaunch: !Ref MapPublicIpOnLaunch
      VpcId: !Ref VpcId
      Tags:
      - Key: Name
        Value: !Sub "${ProjectName}-${EnvironmentName}-${SubnetName}"

Outputs:
  SubnetId:
    Description: "Id of the Subnet"
    Value: !Ref Subnet
  CidrBlock:
    Description: "CidrBlock of the Subnet"
    Value: !GetAtt Subnet.CidrBlock
