---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Tables and Route Tables

Parameters:
  # Global parameters
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"

  # Stack parameters
  VPCId:
    Type: String
  RouteTableName:
    Type: String
  SubnetId:
    Type: String

Resources:  
  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref VPCId
      Tags:
        - Key: Name
          Value: !Sub "${ProjectName}-${EnvironmentName}-${RouteTableName}-RT"

  SubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref RouteTable
      SubnetId: !Ref SubnetId

Outputs:
  RouteTableId:
    Description: "ID of the Root Table"
    Value: !Ref RouteTable
  SubnetRouteTableAssociationId:
    Description: "ID of the Root Table Association"
    Value: !Ref SubnetRouteTableAssociation
