---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template VPC Endpoint Service for NLB or GLB

Parameters:
  # Stack parameters
  AcceptanceRequired:
    Description: "Indicates whether requests from service consumers to create an endpoint to your service must be accepted."
    Type: String
    Default: false
    AllowedValues:
      - true
      - false
  GatewayLoadBalancerArn:
    Description: "The Amazon Resource Names (ARNs) of the Gateway Load Balancers."
    Type: String
    Default: ""
  NetworkLoadBalancerArn:
    Description: "The Amazon Resource Names (ARNs) of the Network Load Balancers."
    Type: String
    Default: ""
  VPCESType:
    Type: String
    Default: network
    AllowedValues:
      - network
      - gateway

Conditions:
  isNetworkType: !Equals [ !Ref VPCESType, network ]
  isGatewayType: !Equals [ !Ref VPCESType, gateway ]

Resources:
  NLBEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Condition: isNetworkType
    Properties:
      AcceptanceRequired: !Ref AcceptanceRequired
      NetworkLoadBalancerArns: 
        - !Ref NetworkLoadBalancerArn

  GLBEndpointService:
    Type: AWS::EC2::VPCEndpointService
    Condition: isGatewayType
    Properties:
      AcceptanceRequired: !Ref AcceptanceRequired
      NetworkLoadBalancerArns: 
        - !Ref GatewayLoadBalancerArn

Outputs:
  VPCEndpointServiceId:
    Description: "Returns the ID of the VPC endpoint service configuration."
    Value: !If [ isNetworkType, !Ref NLBEndpointService, !Ref GLBEndpointService ]