---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template VPC Endpoint Service for NLB or GLB

Parameters:
  # Stack parameters
  ServiceName:
    Description: "The name of the endpoint service."
    Type: String
  SecurityGroupId:
    Description: "The Security Group for VPC Endpoint."
    Type: String
  SubnetId:
    Type: String
  VpcId:
    Type: String
  VpcEndpointType:
    Description: "The type of endpoint."
    Type: String
    Default: "Gateway"
    AllowedValues:
      - "Interface"
      - "Gateway"
      - "GatewayLoadBalancer"

Resources:
  VpcEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      PrivateDnsEnabled: false
      SecurityGroupIds:
        - !Ref SecurityGroupId
      ServiceName: !Ref ServiceName
      SubnetIds: 
        - !Ref SubnetId
      VpcEndpointType: !Ref VpcEndpointType
      VpcId: !Ref VpcId


Outputs:
  VPCEndpointId:
    Description: "Returns the ID of the VPC endpoint."
    Value: !Ref VpcEndpoint