---
AWSTemplateFormatVersion: "2010-09-09"
Description: This template create Instance

Parameters:
  # Global parameters
  Bucket:
    Description: "CloudFormation bucket URL"
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: "Key to find object in the bucket"
    Type: String
    Default: "91_SiteToSiteVpn"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  AvailabilityZone:
    Description: "AZ of the Instance"
    Type: String
  ImageId:
    Description: "Instance AMI"
    Type: String
  InstanceName:
    Description: "Instance name"
    Type: String
  IamInstanceProfile: 
    Default: ""
    Description: "Instance Profile"
    Type: String   
  InstanceType:
    Description: "Instance type"
    Type: String
  KeyName:
    Description: "SSH key to connect to the instance"
    Type: String
  SecurityGroup:
    Description: "InstanceSecurity Groups"
    Type: String
  SubnetId:
    Description: "Instance Subnet ID"
    Type: String

Conditions:
  IsEuWest3: !Equals [!Ref "AWS::Region", "eu-west-3" ]

Resources:
  Instance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Ref AvailabilityZone
        ElasticIP: !If 
          - IsEuWest3
          - "true"
          - "false"
        ImageId: !Ref ImageId
        InstanceName: !Ref InstanceName
        IamInstanceProfile: !Ref IamInstanceProfile
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroup: !Ref SecurityGroup
        SourceDestCheck:  !If 
          - IsEuWest3
          - "false"
          - "true"
        SubnetId: !Ref SubnetId

Outputs:
  InstanceId:
    Description: "Id of the Instance"
    Value: !GetAtt Instance.Outputs.InstanceId
  PrivateIP:
    Description: "Private IP of the Instance"
    Value: !GetAtt Instance.Outputs.InstancePrivateIP
