# aws cloudformation validate-template --template-body file:/19_ROOT_NatGateway.yaml
# aws cloudformation create-stack --stack-name ANS-19 --template-body file:/19_ROOT_NatGateway.yaml --region eu-west-3 --capabilities CAPABILITY_IAM
# aws cloudformation delete-stack --stack-name ANS-19 --region eu-west-3

AWSTemplateFormatVersion: "2010-09-09"
Description: This template deploys a VPC, Private Subnet, Public Subnets, Bastion and Application

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: "Project Configuration"
        Parameters:
          - ProjectName
          - EnvironmentName
      - Label:
          default: "Configuration"
        Parameters:
          - Bucket
          - BucketKey
          - BucketObject
          - SaveInS3File
      - Label:
          default: "VPC configuration"
        Parameters:
          - VpcName
          - VpcCidrBlock
      - Label:
          default: "Subnets configuration"
        Parameters:
          - SubnetName
          - SubnetPrivateCidrBlock
          - SubnetPublicCidrBlock
      - Label:
          default: "IGW, Route Tables and Routes"
        Parameters:
          - InternetGatewayName
          - NatGatewayName
      - Label:
          default: "Instances"
        Parameters:
          - KeyName
          - ApplicationInstanceImageId
          - ApplicationInstanceName
          - ApplicationInstanceType
          - BastionInstanceImageId
          - BastionInstanceName
          - BastionInstanceType

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "19_NatGateway"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: ["dev", "test", "staging", "prod"]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "true"
    Description: "Save resources information in s3 file"
    Type: String

  # Network parameters
  InternetGatewayName:
    Default: "VPC-IGW"
    Type: String
  NatGatewayName:
    Default: "VPC-NGW"
    Type: String

  SubnetName:
    Default: "Subnet"
    Description: Subnet name
    Type: String
  SubnetPrivateCidrBlock:
    Default: 10.100.1.0/24
    Description: "Private Subnet CIDR"
    Type: String
  SubnetPublicCidrBlock:
    Default: 10.100.0.0/24
    Description: "Public Subnet CIDR"
    Type: String

  VpcName:
    Default: "MyVPC"
    Description: VPC name
    Type: String
  VpcCidrBlock:
    Default: 10.100.0.0/16
    Description: "The IPv4 network range for the VPC, in CIDR notation."
    Type: String

  # Instances parameters
  ApplicationInstanceImageId:
    Default: ami-08461dc8cd9e834e0
    Description: "Application Instance AMI"
    Type: AWS::EC2::Image::Id
  ApplicationInstanceName:
    Default: "Application"
    Description: "Application Instances name"
    Type: String
  ApplicationInstanceType:
    Default: t2.micro
    Description: "Application Instances type"
    Type: String
  BastionInstanceImageId:
    Default: ami-08461dc8cd9e834e0
    Description: "Bastion Instance AMI"
    Type: AWS::EC2::Image::Id
  BastionInstanceName:
    Default: "Bastion"
    Description: "Bastion Instances name"
    Type: String
  BastionInstanceType:
    Default: t2.micro
    Description: "Bastion Instances type"
    Type: String
  KeyName:
    Default: "dso-paris"
    Description: "Instances Key name"
    Type: String

Resources:
  Lambdas:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Retain
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_Lambdas.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        ApplicationLogLevel: ERROR

  Roles:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - Lambdas
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_Roles.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File

  VpcAndSubnets:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - Roles
      - Lambdas
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_VpcAndSubnets.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        SubnetPublicCidrBlock: !Ref SubnetPublicCidrBlock
        SubnetPrivateCidrBlock: !Ref SubnetPrivateCidrBlock
        SubnetName: !Ref SubnetName
        VpcCidrBlock: !Ref VpcCidrBlock
        VpcName: !Ref VpcName
        
# Create Internet Gateway and default route table for public subnet
  Gateways:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - Roles
      - Lambdas
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_Gateways.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        IgwName: !Ref InternetGatewayName
        NgwName: !Ref NatGatewayName
        SubnetPrivateId: !GetAtt VpcAndSubnets.Outputs.SubnetPrivateId
        SubnetPublicId: !GetAtt VpcAndSubnets.Outputs.SubnetPublicId
        VpcId: !GetAtt VpcAndSubnets.Outputs.VpcId

  RouteTables:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - Roles
      - Lambdas
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_RouteTables.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        InternetGatewayId: !GetAtt Gateways.Outputs.InternetGatewayId
        NatGatewayId: !GetAtt Gateways.Outputs.NatGatewayId
        RouteTableNames: "A,B"
        SubnetPrivateId: !GetAtt VpcAndSubnets.Outputs.SubnetPrivateId
        SubnetPublicId: !GetAtt VpcAndSubnets.Outputs.SubnetPublicId
        VpcId: !GetAtt VpcAndSubnets.Outputs.VpcId

  SecurityGroups:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - Roles
      - Lambdas
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_SecurityGroups.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        ApplicationInstanceIngressCidrIp: "10.0.0.0/8"
        ApplicationInstanceVpcId: !GetAtt VpcAndSubnets.Outputs.VpcId
        BastionInstanceIngressCidrIp: "0.0.0.0/0"
        BastionInstanceVpcId: !GetAtt VpcAndSubnets.Outputs.VpcId
        VpcCidrBlock: !Ref VpcCidrBlock

  Instances:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    DependsOn:
      - Lambdas
      - Gateways
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/${BucketKey}/19_Instances.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        ApplicationInstanceImageId: !Ref ApplicationInstanceImageId
        ApplicationInstanceName: !Ref ApplicationInstanceName
        ApplicationInstanceProfile: !GetAtt Roles.Outputs.InstanceProfileId
        ApplicationInstanceType: !Ref ApplicationInstanceType
        ApplicationInstanceSecurityGroup: !GetAtt SecurityGroups.Outputs.ApplicationInstanceSecurityGroupId
        ApplicationInstanceSubnetId: !GetAtt VpcAndSubnets.Outputs.SubnetPrivateId
        BastionInstanceImageId: !Ref BastionInstanceImageId
        BastionInstanceName: !Ref BastionInstanceName
        BastionInstanceType: !Ref BastionInstanceType
        BastionInstanceSecurityGroup: !GetAtt SecurityGroups.Outputs.BastionInstanceSecurityGroupId
        BastionInstanceSubnetId: !GetAtt VpcAndSubnets.Outputs.SubnetPublicId
        KeyName: !Ref KeyName