AWSTemplateFormatVersion: "2010-09-09"
Description: "Create an AMI from an EC2 instance."

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "64_VPCEndpointServiceAndAccessThroughVPCEndpoint"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: ["dev", "test", "staging", "prod"]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  AvailabilityZone: # Required: No
    Description: >-
      The Availability Zone of the instance. If not specified, an Availability
      Zone will be automatically chosen for you based on the load balancing
      criteria for the Region. This parameter is not supported by
      DescribeImageAttribute.
    Type: String
  ElasticIP:
    AllowedValues:
      - "false"
      - "true"
    Default: "false"
    Description: "Create elastic IP for the instance"
    Type: String
  IamInstanceProfile: # Required: No
    Default: ""
    Description: >-
      The name of an IAM instance profile. To create a new IAM instance profile,
      use the AWS::IAM::InstanceProfile resource.
    Type: String
  ImageId: # Required: Conditional
    Default: ami-08461dc8cd9e834e0
    Description: >-
      The ID of the AMI. An AMI ID is required to launch an instance and must
      be specified here or in a launch template.
    Type: AWS::EC2::Image::Id
  InstanceName:
    Description: "Instance name"
    Type: String
  InstanceType: # Required: No
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.large
    Default: t2.micro
    Description: >-
      The instance type. For more information, see Instance types in the Amazon
      EC2 User Guide. When you change your EBS-backed instance type, instance
      restart or replacement behavior depends on the instance type
      compatibility between the old and new types. An instance with an instance
      store volume as the root volume is always replaced. For more information,
      see Change the instance type in the Amazon EC2 User Guide.
    Type: String
  KeyName: # Required: No
    Default: "dso-paris"
    Description: >-
      The name of the key pair. You can create a key pair using CreateKeyPair
      or ImportKeyPair.
    Type: String
  SecurityGroupIds: # Required: Conditional
    Default: ""
    Description: >-
      The IDs of the security groups. You can specify the IDs of existing
      security groups and references to resources created by the stack
      template. If you specify a network interface, you must specify any
      security groups as part of the network interface.
    Type: CommaDelimitedList
  SourceDestCheck: # Required: No
    AllowedValues:
      - "false"
      - "true"
    Default: "true"
    Description: >-
      Enable or disable source/destination checks, which ensure that the
      instance is either the source or the destination of any traffic that it
      receives. If the value is true, source/destination checks are enabled;
      otherwise, they are disabled. The default value is true. You must
      disable source/destination checks if the instance runs services such as
      network address translation, routing, or firewalls.
    Type: String
  SubnetId: # Required: No
    Description: >-
      The ID of the subnet to launch the instance into. If you specify a
      network interface, you must specify any subnets as part of the network
      interface instead of using this parameter.
    Type: String
  UserData: # Required: No
    Default: ""
    Description: >-
      The parameters or scripts to store as user data. Any scripts in user data
      are run when you launch the instance. User data is limited to 16 KB. You
      must provide base64-encoded text. For more information, see Fn::Base64.
      If the root volume is an EBS volume and you update user data,
      CloudFormation restarts the instance. If the root volume is an instance
      store volume and you update user data, the instance is replaced.
    Type: String

Resources:
  # Completes when the instance is fully provisioned and ready for AMI creation.
  InstanceForAmi:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 10
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: "false"
        AvailabilityZone: !Select [0, !GetAZs ]
        IamInstanceProfile: !Ref IamInstanceProfile
        ImageId: !Ref ImageId
        InstanceName: !Ref InstanceName
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds: !Ref SecurityGroupIds
        SubnetId: !Ref SubnetId
        UserData: !Ref UserData

  AMI:
    Type: Custom::AMI
    DependsOn: AMICreate
    Properties:
      ServiceToken: !GetAtt AMIFunction.Arn
      InstanceId: !Ref Instance

  AMIFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: !Sub |
          var response = require('cfn-response');
          var AWS = require('aws-sdk');
          exports.handler = function(event, context) {
            console.log("Request received:\n", JSON.stringify(event));
            var physicalId = event.PhysicalResourceId;
            function success(data) {
              return response.send(event, context, response.SUCCESS, data, physicalId);
            }
            function failed(e) {
              return response.send(event, context, response.FAILED, e, physicalId);
            }
            // Call ec2.waitFor, continuing if not finished before Lambda function timeout.
            function wait(waiter) {
              console.log("Waiting: ", JSON.stringify(waiter));
              event.waiter = waiter;
              event.PhysicalResourceId = physicalId;
              var request = ec2.waitFor(waiter.state, waiter.params);
              setTimeout(()=>{
                request.abort();
                console.log("Timeout reached, continuing function. Params:\n", JSON.stringify(event));
                var lambda = new AWS.Lambda();
                lambda.invoke({
                  FunctionName: context.invokedFunctionArn,
                  InvocationType: 'Event',
                  Payload: JSON.stringify(event)
                }).promise().then((data)=>context.done()).catch((err)=>context.fail(err));
              }, context.getRemainingTimeInMillis() - 5000);
              return request.promise().catch((err)=>
                (err.code == 'RequestAbortedError') ?
                  new Promise(()=>context.done()) :
                  Promise.reject(err)
              );
            }
            var ec2 = new AWS.EC2(),
                instanceId = event.ResourceProperties.InstanceId;
            if (event.waiter) {
              wait(event.waiter).then((data)=>success({})).catch((err)=>failed(err));
            } else if (event.RequestType == 'Create' || event.RequestType == 'Update') {
              if (!instanceId) { failed('InstanceID required'); }
              ec2.waitFor('instanceStopped', {InstanceIds: [instanceId]}).promise()
              .then((data)=>
                ec2.createImage({
                  InstanceId: instanceId,
                  Name: event.RequestId
                }).promise()
              ).then((data)=>
                wait({
                  state: 'imageAvailable',
                  params: {ImageIds: [physicalId = data.ImageId]}
                })
              ).then((data)=>success({})).catch((err)=>failed(err));
            } else if (event.RequestType == 'Delete') {
              if (physicalId.indexOf('ami-') !== 0) { return success({});}
              ec2.describeImages({ImageIds: [physicalId]}).promise()
              .then((data)=>
                (data.Images.length == 0) ? success({}) :
                ec2.deregisterImage({ImageId: physicalId}).promise()
              ).then((data)=>
                ec2.describeSnapshots({Filters: [{
                  Name: 'description',
                  Values: ["*" + physicalId + "*"]
                }]}).promise()
              ).then((data)=>
                (data.Snapshots.length === 0) ? success({}) :
                ec2.deleteSnapshot({SnapshotId: data.Snapshots[0].SnapshotId}).promise()
              ).then((data)=>success({})).catch((err)=>failed(err));
            }
          };
      Runtime: nodejs20.x
      Timeout: 300
  
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal: {Service: [lambda.amazonaws.com]}
          Action: ['sts:AssumeRole']
      Path: /
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      - arn:aws:iam::aws:policy/service-role/AWSLambdaRole
      Policies:
      - PolicyName: EC2Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeImages'
              - 'ec2:CreateImage'
              - 'ec2:DeregisterImage'
              - 'ec2:DescribeSnapshots'
              - 'ec2:DeleteSnapshot'
              Resource: ['*']
Outputs:
  AmiId:
    Value: !Ref AMI