---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create SSM Document to deploy Apache Httpd

Parameters:
  # Global parameters
  Bucket:
    Description: "CloudFormation bucket URL"
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: "Key to find object in the bucket"
    Type: String
    Default: "64_VPCEndpointServiceAndAccessThroughVPCEndpoint"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

Resources:
  ApacheHttpdSSMDocument:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/SSM/ApacheHttpdSSMDocument.yaml"
      TimeoutInMinutes: 10

Outputs:
  SSMDocumentName:
    Description: "Name of the created SSM Document"
    Value: !GetAtt ApacheHttpdSSMDocument.Outputs.SSMDocumentName
  
  SSMDocumentArn:
    Description: "ARN of the created SSM Document"
    Value: !GetAtt ApacheHttpdSSMDocument.Outputs.SSMDocumentArn
