---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys a VPC, and Subnets

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: "Key to find object in the bucket"
    Type: String
    Default: "64_VPCEndpointServiceAndAccessThroughVPCEndpoint"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  BucketRegion:
    AllowedValues: ["eu-west-3", "eu-central-1"]
    Default: "eu-west-3"
    Description: "Region where is the Bucket"
    Type: String
  EnvironmentName:
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String
  
# Stack parameters
  VpcCidrBlocks:
    Description: "The IPv4 network range for the VPCs, in CIDR notation."
    Type: CommaDelimitedList
  VpcNames:
    Description: "VPC names"
    Type: CommaDelimitedList

Resources:
  # A VPC Consumer
  VpcAStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Vpc.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        CidrBlock: !Select [0, !Ref VpcCidrBlocks]
        VpcName: !Select [0, !Ref VpcNames]

  VpcAPublicSubnetStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        CidrBlock: !Select [ 0, !Cidr [!GetAtt VpcAStack.Outputs.VpcCidrBlock, 6, 8]]
        MapPublicIpOnLaunch: true
        SubnetName: !Join ["-", [!Select [0, !Ref VpcNames], "Public"]]
        VpcId: !GetAtt VpcAStack.Outputs.VpcId

  VpcAPrivateSubnetAStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        CidrBlock: !Select [ 1, !Cidr [!GetAtt VpcAStack.Outputs.VpcCidrBlock, 6, 8]]
        SubnetName: !Join ["-", [!Select [0, !Ref VpcNames], "A-Private"]]
        VpcId: !GetAtt VpcAStack.Outputs.VpcId

  VpcAPrivateSubnetBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        CidrBlock: !Select [ 3, !Cidr [!GetAtt VpcAStack.Outputs.VpcCidrBlock, 6, 8]]
        SubnetName: !Join ["-", [!Select [0, !Ref VpcNames], "B-Private"]]
        VpcId: !GetAtt VpcAStack.Outputs.VpcId

  VpcAPrivateSubnetCStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        CidrBlock: !Select [ 5, !Cidr [!GetAtt VpcAStack.Outputs.VpcCidrBlock, 6, 8]]
        SubnetName: !Join ["-", [!Select [0, !Ref VpcNames], "C-Private"]]
        VpcId: !GetAtt VpcAStack.Outputs.VpcId

  VpcAPrivateSubnetDStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [1, !GetAZs ]
        CidrBlock: !Select [ 2, !Cidr [!GetAtt VpcAStack.Outputs.VpcCidrBlock, 6, 8]]
        SubnetName: !Join ["-", [!Select [0, !Ref VpcNames], "D-Private"]]
        VpcId: !GetAtt VpcAStack.Outputs.VpcId

  # B VPC Provider
  VpcBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Vpc.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        CidrBlock: !Select [1, !Ref VpcCidrBlocks]
        VpcName: !Select [1, !Ref VpcNames]

  VpcBPrivateSubnetAStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        CidrBlock: !Select [ 1, !Cidr [!GetAtt VpcBStack.Outputs.VpcCidrBlock, 5, 8]]
        SubnetName: !Join ["-", [!Select [1, !Ref VpcNames], "A-Private"]]
        VpcId: !GetAtt VpcBStack.Outputs.VpcId

  VpcBPrivateSubnetBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [0, !GetAZs ]
        CidrBlock: !Select [ 3, !Cidr [!GetAtt VpcBStack.Outputs.VpcCidrBlock, 5, 8]]
        SubnetName: !Join ["-", [!Select [1, !Ref VpcNames], "B-Private"]]
        VpcId: !GetAtt VpcBStack.Outputs.VpcId

  VpcBPrivateSubnetCStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [1, !GetAZs ]
        CidrBlock: !Select [ 2, !Cidr [!GetAtt VpcBStack.Outputs.VpcCidrBlock, 5, 8]]
        SubnetName: !Join ["-", [!Select [1, !Ref VpcNames], "C-Private"]]
        VpcId: !GetAtt VpcBStack.Outputs.VpcId

  VpcBPrivateSubnetDStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [1, !GetAZs ]
        CidrBlock: !Select [ 4, !Cidr [!GetAtt VpcBStack.Outputs.VpcCidrBlock, 5, 8]]
        SubnetName: !Join ["-", [!Select [1, !Ref VpcNames], "D-Private"]]
        VpcId: !GetAtt VpcBStack.Outputs.VpcId

Outputs:
  VpcIds:
    Description: "Id of the VPCs"
    Value: !Join 
      - ","
      - - !GetAtt VpcAStack.Outputs.VpcId
        - !GetAtt VpcBStack.Outputs.VpcId
  VpcAPublicSubnetId:
    Description: "Id of the VPC A Public Subnet"
    Value: !GetAtt VpcAPublicSubnetStack.Outputs.SubnetId
  VpcAPublicSubnetCidr:
    Description: "Cidr of VPC A Public Subnet"
    Value: !GetAtt VpcAPublicSubnetStack.Outputs.SubnetCidrBlock
  VpcAPrivateSubnetIds:
    Description: "Ids of the VPC A Private Subnets"
    Value: !Join 
      - ","
      - - !GetAtt VpcAPrivateSubnetAStack.Outputs.SubnetId
        - !GetAtt VpcAPrivateSubnetBStack.Outputs.SubnetId
        - !GetAtt VpcAPrivateSubnetCStack.Outputs.SubnetId
        - !GetAtt VpcAPrivateSubnetDStack.Outputs.SubnetId
  VpcAPrivateSubnetCidrs:
    Description: "Cidrs of VPC A Private Subnets"
    Value: !Join 
      - ","
      - - !GetAtt VpcAPrivateSubnetAStack.Outputs.SubnetCidrBlock
        - !GetAtt VpcAPrivateSubnetBStack.Outputs.SubnetCidrBlock
        - !GetAtt VpcAPrivateSubnetCStack.Outputs.SubnetCidrBlock
        - !GetAtt VpcAPrivateSubnetDStack.Outputs.SubnetCidrBlock
  VpcBPrivateSubnetIds:
    Description: "Ids of the VPC B Private Subnets"
    Value: !Join 
      - ","
      - - !GetAtt VpcBPrivateSubnetAStack.Outputs.SubnetId
        - !GetAtt VpcBPrivateSubnetBStack.Outputs.SubnetId
        - !GetAtt VpcBPrivateSubnetCStack.Outputs.SubnetId
        - !GetAtt VpcBPrivateSubnetDStack.Outputs.SubnetId
  VpcBPrivateSubnetCidrs:
    Description: "Cidrs of VPC B Private Subnets"
    Value: !Join 
      - ","
      - - !GetAtt VpcBPrivateSubnetAStack.Outputs.SubnetCidrBlock
        - !GetAtt VpcBPrivateSubnetBStack.Outputs.SubnetCidrBlock
        - !GetAtt VpcBPrivateSubnetCStack.Outputs.SubnetCidrBlock
        - !GetAtt VpcBPrivateSubnetDStack.Outputs.SubnetCidrBlock
