---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploy Lambda to use

Parameters:
  # Stack parameters
  Bucket:
    Default: "hawkfund-cloudformation"  
    Description: "CloudFormation bucket URL"
    Type: String
  BucketKey:
    Default: "90_SiteToSiteVpn"
    Description: "Key to find object in the bucket"
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  CloudRegion:
    Description: "Region of the Cloud infrastructure"
    Type: String

Conditions:
  IsCloudInfra: !Equals [!Ref "AWS::Region", !Ref CloudRegion ]

Resources:
  # For all Regions
  GetParametersFromS3:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/GetParametersFromS3.yaml"
      TimeoutInMinutes: 5

  UpdateParametersFromS3:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/UpdateParametersFromS3.yaml"
      TimeoutInMinutes: 5

  # Only for eu-central-1
  CustomerGatewayParametersToS3:
    Type: AWS::CloudFormation::Stack
    Condition: IsCloudInfra
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/CustomerGatewayParametersToS3.yaml"
      TimeoutInMinutes: 5

  VpnConnectionParametersToS3:
    Type: AWS::CloudFormation::Stack
    Condition: IsCloudInfra
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/VpnConnectionParametersToS3.yaml"
      TimeoutInMinutes: 5