---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploy Lambda to use

Parameters:
  # Stack parameters
  Bucket:
    Default: "hawkfund-cloudformation"  
    Description: "CloudFormation bucket URL"
    Type: String
  BucketKey:
    Default: "90_SiteToSiteVpn"
    Description: "Key to find object in the bucket"
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  CloudRegion:
    Description: "Region of the Cloud infrastructure"
    Type: String

Conditions:
  IsCloudInfra: !Equals [!Ref "AWS::Region", !Ref CloudRegion ]

Resources:
  # For all Regions
  GetParametersFromS3Stack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/GetParametersFromS3.yaml"
      TimeoutInMinutes: 5

  UpdateParametersFromS3Stack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/UpdateParametersFromS3.yaml"
      TimeoutInMinutes: 5

  # Only for eu-central-1
  CustomerGatewayParametersToS3Stack:
    Type: AWS::CloudFormation::Stack
    Condition: IsCloudInfra
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/CustomerGatewayParametersToS3.yaml"
      TimeoutInMinutes: 5

  VpnConnectionParametersToS3Stack:
    Type: AWS::CloudFormation::Stack
    Condition: IsCloudInfra
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/VpnConnectionParametersToS3.yaml"
      TimeoutInMinutes: 5

Outputs:
  GetParametersFromS3Arn:
    Description: ARN of GetParametersFromS3 Lambda
    Value: !GetAtt GetParametersFromS3Stack.Outputs.LambdaFunctionArn
  UpdateParametersFromS3Arn:
    Description: ARN of UpdateParametersFromS3 Lambda
    Value: !GetAtt UpdateParametersFromS3Stack.Outputs.LambdaFunctionArn
  CustomerGatewayParametersToS3Arn:
    Description: ARN of CustomerGatewayParametersToS3 Lambda
    Value: !If
      - IsCloudInfra
      - !GetAtt CustomerGatewayParametersToS3Stack.Outputs.LambdaFunctionArn
      - ""
  VpnConnectionParametersToS3Arn:
    Description: ARN of VpnConnectionParametersToS3 Lambda
    Value: !If
      - IsCloudInfra
      - !GetAtt VpnConnectionParametersToS3Stack.Outputs.LambdaFunctionArn
      - ""