---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploy Roles

Parameters:
  # Global parameters
  Bucket:
    Description: "CloudFormation bucket URL"
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: "Key to find object in the bucket"
    Type: String
    Default: "90_SiteToSiteVpn"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"

Resources:
  CustomerGatewayParametersToS3RoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/IAM/CustomerGatewayParametersToS3Role.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject

  GetParametersFromS3RoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/IAM/GetParametersFromS3Role.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject

  UpdateParametersFromS3RoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/IAM/UpdateParametersFromS3Role.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject

  VpnConnectionParametersToS3RoleStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/IAM/VpnConnectionParametersToS3Role.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject

  InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      InstanceProfileName: !Sub "${ProjectName}-${EnvironmentName}-InstanceProfile"
      Path: "/"
      Roles: 
        - Ref: AmazonSSMManagedInstanceCoreRole

  AmazonSSMManagedInstanceCoreRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
      RoleName: "AmazonSSMManagedInstanceCore-Role"
      Tags:
        - Key: Name
          Value: "AmazonSSMManagedInstanceCore-Role"

Outputs:
  InstanceProfileId:
    Description: "Instance Profile Id"
    Value: !Ref InstanceProfile

  CustomerGatewayParametersToS3RoleArn:
    Description: "CustomerGatewayParametersToS3Role Lambda Role Arn"
    Value: !GetAtt CustomerGatewayParametersToS3RoleStack.Outputs.RoleArn
  GetParametersFromS3RoleArn:
    Description: "GetParametersFromS3Role Lambda Role Arn"
    Value: !GetAtt GetParametersFromS3RoleStack.Outputs.RoleArn
  UpdateParametersFromS3RoleArn:
    Description: "UpdateParametersFromS3 Lambda Role Arn"
    Value: !GetAtt UpdateParametersFromS3RoleStack.Outputs.RoleArn
  VpnConnectionParametersToS3RoleArn:
    Description: "VpnConnectionParametersToS3Role Lambda Role Arn"
    Value: !GetAtt VpnConnectionParametersToS3RoleStack.Outputs.RoleArn