---
AWSTemplateFormatVersion: "2010-09-09"
Description: This template create bastion and application Instances and Security Groups

Parameters:
  # Global parameters
  Bucket:
    Description: "CloudFormation bucket URL"
    Type: String
    Default: "hawkfund-cloudformation"
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
    Default: "72_TransitGatewayRestrictedRouting"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  EnvironmentName:
    Description: "Environment name that prefix all resources"
    Type: String
    Default: "dev"
    AllowedValues:
      - "dev"
      - "test"
      - "prod"
    ConstraintDescription: Must specify dev, test or prod
  ProjectName:
    Description: "Project name that prefix all resources"
    Type: String
    Default: "ANS"
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  ApplicationInstanceName:
    Description: "Application Instance name"
    Type: String
  ApplicationInstanceSubnetIds:
    Description: "Application Subnet IDs"
    Type: String
  ApplicationInstanceSecurityGroups:
    Description: "Application Security Groups"
    Type: String
  BastionInstanceName:
    Description: "Bastion Instance name"
    Type: String
  BastionInstanceSecurityGroup:
    Description: "Bastion Security Group"
    Type: String
  BastionInstanceSubnetId:
    Description: "Bastion Subnet ID"
    Type: String
  ImageId:
    Default: ami-08461dc8cd9e834e0
    Description: "Instance AMI"
    Type: String
  InstanceType:
    Default: t2.micro
    Description: "Instances type"
    Type: String
  KeyName:
    Default: "dso-paris"
    Description: "Instances Key name"
    Type: String

Resources:
  BastionInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [ 0, !GetAZs ]
        ElasticIP: "true"
        ImageId: !Ref ImageId
        InstanceName: !Ref BastionInstanceName
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroupIds: !Ref BastionInstanceSecurityGroup
        SubnetId: !Ref BastionInstanceSubnetId

  ApplicationAInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [ 0, !GetAZs ]
        ImageId: !Ref ImageId
        InstanceName: !Sub "${ApplicationInstanceName}-A"
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroup: !Select [ 0, !Split [ ",", !Ref ApplicationInstanceSecurityGroups ] ]
        SubnetId: !Select [ 0, !Split [ ",", !Ref ApplicationInstanceSubnetIds ] ]

  ApplicationBInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [ 1, !GetAZs ]
        ImageId: !Ref ImageId
        InstanceName: !Sub "${ApplicationInstanceName}-B"
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroup: !Select [ 1, !Split [ ",", !Ref ApplicationInstanceSecurityGroups ] ]
        SubnetId: !Select [ 1, !Split [ ",", !Ref ApplicationInstanceSubnetIds ] ]

  ApplicationCInstance:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/EC2/Instance.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Select [ 2, !GetAZs ]
        ImageId: !Ref ImageId
        InstanceName: !Sub "${ApplicationInstanceName}-C"
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        SecurityGroup: !Select [2, !Split [",", !Ref ApplicationInstanceSecurityGroups]]
        SubnetId: !Select [2, !Split [",", !Ref ApplicationInstanceSubnetIds]]

Outputs:
  BastionInstancesId:
    Description: "Id of the Bastion Instance"
    Value: !GetAtt BastionInstance.Outputs.InstanceId
  BastionPrivateIP:
    Description: "Private IP of the Bastion Instance"
    Value: !GetAtt BastionInstance.Outputs.InstancePrivateIP
  BastionPublicIP:
    Description: "Public IP of the Bastion Instance"
    Value: !GetAtt BastionInstance.Outputs.InstancePublicIP
  ApplicationAInstanceId:
    Description: "Id of the Application A Instance"
    Value: !GetAtt ApplicationAInstance.Outputs.InstanceId
  ApplicationAPrivateIP:
    Description: "Private IP of the Application A Instance"
    Value: !GetAtt ApplicationAInstance.Outputs.InstancePrivateIP
  ApplicationBInstanceId:
    Description: "Id of the Application B Instance"
    Value: !GetAtt ApplicationBInstance.Outputs.InstanceId
  ApplicationBPrivateIP:
    Description: "Private IP of the Application B Instance"
    Value: !GetAtt ApplicationBInstance.Outputs.InstancePrivateIP
  ApplicationCInstanceId:
    Description: "Id of the Application C Instance"
    Value: !GetAtt ApplicationCInstance.Outputs.InstanceId
  ApplicationCPrivateIP:
    Description: "Private IP of the Application C Instance"
    Value: !GetAtt ApplicationCInstance.Outputs.InstancePrivateIP
