---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploy Lambda to use

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Description: Key to find object in the bucket
    Type: String
    Default: "72_TransitGatewayRestrictedRouting"
  BucketObject:
    Description: "File to store data in the bucket"
    Type: String
    Default: "Data.json"
  EnvironmentName:
    AllowedValues: [ "dev", "test", "prod" ]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  ApplicationLogLevel:
    AllowedValues: [ TRACE, DEBUG, INFO, WARN, ERROR, FATAL ]
    Default: ERROR
    Description: |
      Set this property to filter the application logs for your function that Lambda sends to CloudWatch. 
      Lambda only sends application logs at the selected level of detail and lower, 
      where TRACE is the highest level and FATAL is the lowest.
    Type: String

Resources:
  EC2ResourceToS3Stack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        ApplicationLogLevel: !Ref ApplicationLogLevel
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/EC2ResourceToS3.yaml"
      TimeoutInMinutes: 5

  UpdateParametersFromS3Stack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        ApplicationLogLevel: !Ref ApplicationLogLevel
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/Lambda/UpdateParametersFromS3.yaml"
      TimeoutInMinutes: 5

Outputs:
  EC2ResourceToS3LambdaFunctionArn:
    Description: "EC2ResourceToS3 Lambda Arn"
    Value: !GetAtt EC2ResourceToS3Stack.Outputs.LambdaFunctionArn
  EC2ResourceToS3RoleArn:
    Description: "EC2ResourceToS3 Lambda Role Arn"
    Value: !GetAtt EC2ResourceToS3Stack.Outputs.RoleArn
  EC2ResourceToS3LogGroupId:
    Description: EC2ResourceToS3 Lambda Log Group Id
    Value: !GetAtt EC2ResourceToS3Stack.Outputs.LogGroupId

  UpdateParametersFromS3LambdaFunctionArn:
    Description: "ARN of UpdateParametersFromS3 Lambda"
    Value: !GetAtt UpdateParametersFromS3Stack.Outputs.LambdaFunctionArn
  UpdateParametersFromS3RoleArn:
    Description: "UpdateParametersFromS3 Lambda Role Arn"
    Value: !GetAtt UpdateParametersFromS3Stack.Outputs.RoleArn
  UpdateParametersFromS3LogGroupId:
    Description: UpdateParametersFromS3 Lambda Log Group Id
    Value: !GetAtt UpdateParametersFromS3Stack.Outputs.LogGroupId
