---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template create Tables and Route Tables

Parameters:
# Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "72_TransitGatewayRestrictedRouting"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  EnvironmentName:
    AllowedValues: [ "dev", "test", "prod" ]
    ConstraintDescription: "Must specify dev, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String    
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: [ "false", "true" ]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String

  # Stack parameters
  DestinationCidrBlock:
    Description: "CIDR range of VPC"
    Type: String
  VpcIds:
    Description: "VPC IDs"
    Type: String
  SubnetPrivateIds:
    Description: "Private Subnets IDs"
    Type: String
  SubnetPublicId:
    Description: "Public Subnets ID"
    Type: String
  RouteTableNames:
    Description: "Names of all Route Tables"
    Type: String
  InternetGatewayId:
    Description: "Internet Gateway ID"
    Type: String
  TransitGatewayId:
    Description: "Transit Gateway ID"
    Type: String

Resources:  
  SubnetAPublicRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Join [ "-", [ !Select [ 0, !Split [ ",", !Ref RouteTableNames ] ], "Public" ] ]
        SubnetId: !Ref SubnetPublicId
        VpcId: !Select [ 0, !Split [ ",", !Ref VpcIds ] ]

  SubnetAPublicRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableId: !GetAtt SubnetAPublicRouteTableStack.Outputs.RouteTableId
        DestinationCidrBlock: "0.0.0.0/0"
        DestinationType: "InternetGateway"
        GatewayId: !Ref InternetGatewayId

  SubnetAPrivateRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Join [ "-", [ !Select [ 0, !Split [ ",", !Ref RouteTableNames ] ], "Private" ] ]
        SubnetId: !Select [ 0, !Split [ ",", !Ref SubnetPrivateIds ] ]
        VpcId: !Select [ 0, !Split [ ",", !Ref VpcIds ] ]

  SubnetAPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: !Ref DestinationCidrBlock
        DestinationType: "TransitGateway"
        RouteTableId: !GetAtt SubnetAPrivateRouteTableStack.Outputs.RouteTableId
        TransitGatewayId: !Ref TransitGatewayId

  SubnetBPrivateRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        RouteTableName: !Join [ "-", [ !Select [ 1, !Split [ ",", !Ref RouteTableNames ] ], "Private" ] ]
        SubnetId: !Select [ 1, !Split [ ",", !Ref SubnetPrivateIds ] ]
        VpcId: !Select [ 1, !Split [ ",", !Ref VpcIds ] ]

  SubnetBPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: !Ref DestinationCidrBlock
        DestinationType: "TransitGateway"
        RouteTableId: !GetAtt SubnetBPrivateRouteTableStack.Outputs.RouteTableId
        TransitGatewayId: !Ref TransitGatewayId

  SubnetCPrivateRouteTableStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/RouteTable.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        SaveInS3File: !Ref SaveInS3File
        ProjectName: !Ref ProjectName
        RouteTableName: !Join [ "-", [ !Select [ 2, !Split [ ",", !Ref RouteTableNames ] ], "Private" ] ]
        SubnetId: !Select [ 2, !Split [ ",", !Ref SubnetPrivateIds ] ]
        VpcId: !Select [ 2, !Split [ ",", !Ref VpcIds ] ]

  SubnetCPrivateRouteStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.eu-west-3.amazonaws.com/Generic/VPC/Route.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        DestinationCidrBlock: !Ref DestinationCidrBlock
        DestinationType: "TransitGateway"
        RouteTableId: !GetAtt SubnetCPrivateRouteTableStack.Outputs.RouteTableId
        TransitGatewayId: !Ref TransitGatewayId

Outputs:
  SubnetPrivateRouteTableIds:
    Description: "Private Subnet Route Table IDs"
    Value: !Join
      - ","
      - - !GetAtt SubnetAPrivateRouteTableStack.Outputs.RouteTableId
        - !GetAtt SubnetBPrivateRouteTableStack.Outputs.RouteTableId
        - !GetAtt SubnetCPrivateRouteTableStack.Outputs.RouteTableId

  SubnetPrivateRouteTableAssociationIds:
    Description: "Private Route Table Association IDs"
    Value: !Join
      - ","
      - - !GetAtt SubnetAPrivateRouteTableStack.Outputs.SubnetRouteTableAssociationId
        - !GetAtt SubnetBPrivateRouteTableStack.Outputs.SubnetRouteTableAssociationId
        - !GetAtt SubnetCPrivateRouteTableStack.Outputs.SubnetRouteTableAssociationId

  SubnetPublicRouteTableIds:
    Description: "Public Subnet Route IDs"
    Value: !GetAtt SubnetAPublicRouteTableStack.Outputs.RouteTableId

  SubnetPublicRouteTableAssociationIds:
    Description: "Public Route Table Association IDs"
    Value: !GetAtt SubnetAPublicRouteTableStack.Outputs.SubnetRouteTableAssociationId

  GatewayRouteIds:
    Description: "Gateway Route IDs"
    Value: !GetAtt SubnetAPublicRouteStack.Outputs.GatewayRouteId

  TransitGatewayRouteIds:
    Description: "Transit Gateway Route IDs"
    Value: !Join
      - ","
      - - !GetAtt SubnetAPrivateRouteStack.Outputs.TransitGatewayRouteId
        - !GetAtt SubnetBPrivateRouteStack.Outputs.TransitGatewayRouteId
        - !GetAtt SubnetCPrivateRouteStack.Outputs.TransitGatewayRouteId