---
AWSTemplateFormatVersion: "2010-09-09"
Description:  This template deploys a VPC, and Subnets

Parameters:
  # Global parameters
  Bucket:
    Default: "hawkfund-cloudformation"
    Description: CloudFormation buket URL
    Type: String
  BucketKey:
    Default: "110_AWSClientVpn"
    Description: Key to find object in the bucket
    Type: String
  BucketObject:
    Default: "Data.json"
    Description: "File to store data in the bucket"
    Type: String
  BucketRegion:
    AllowedValues: ["eu-west-3", "eu-central-1"]
    Default: "eu-west-3"
    Description: "Region where is the Bucket"
    Type: String
  EnvironmentName:
    AllowedValues: ["dev", "staging", "test", "prod"]
    ConstraintDescription: "Must specify dev, staging, test or prod"
    Default: "dev"
    Description: "Environment name that prefix all resources"
    Type: String
  ProjectName:
    Default: "ANS"
    Description: "Project name that prefix all resources"
    Type: String
  SaveInS3File:
    AllowedValues: ["false", "true"]
    Default: "false"
    Description: "Save resources information in s3 file"
    Type: String
  
# Stack parameters
  AvailabilityZone:
    Description: "The AZ of the subnet"
    Type: String
  SubnetPrivateCidrBlocks:
    Default: "192.168.0.0/24,192.168.100.0/24"
    Description: "Subnets CIDR for Application and VPN Target"
    Type: CommaDelimitedList
  SubnetPrivateNames:
    Default: "Application,VPNTarget"
    Description: Subnet names
    Type: CommaDelimitedList
  SubnetPublicCidrBlock:
    Default: "192.168.200.0/24"
    Description: "Subnets CIDR for Application and VPN Target"
    Type: String
  SubnetPublicName:
    Default: "Bastion"
    Description: Subnet names
    Type: String

  VpcCidrBlock:
    Default: 192.168.0.0/16
    Description: "The IPv4 network range for the VPC, in CIDR notation."
    Type: String
  VpcName:
    Description: "VPC name"
    Type: String

Resources:
  VpcStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Vpc.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        CidrBlock: !Ref VpcCidrBlock
        VpcName: !Ref VpcName

  SubnetPublicStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Ref AvailabilityZone
        CidrBlock: !Ref SubnetPublicCidrBlock
        MapPublicIpOnLaunch: true
        SubnetName: !Ref SubnetPublicName
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  SubnetPrivateAStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Ref AvailabilityZone
        CidrBlock: !Select [ 0, !Ref SubnetPrivateCidrBlocks ]
        MapPublicIpOnLaunch: false
        SubnetName: !Select [ 0, !Ref SubnetPrivateNames ]
        VpcId: !GetAtt VpcStack.Outputs.VpcId

  SubnetPrivateBStack:
    Type: AWS::CloudFormation::Stack
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      TemplateURL: !Sub "https://${Bucket}.s3.${BucketRegion}.amazonaws.com/Generic/VPC/Subnet.yaml"
      TimeoutInMinutes: 5
      Parameters:
        Bucket: !Ref Bucket
        BucketKey: !Ref BucketKey
        BucketObject: !Ref BucketObject
        EnvironmentName: !Ref EnvironmentName
        ProjectName: !Ref ProjectName
        SaveInS3File: !Ref SaveInS3File
        AvailabilityZone: !Ref AvailabilityZone
        CidrBlock: !Select [ 1, !Ref SubnetPrivateCidrBlocks ]
        MapPublicIpOnLaunch: false
        SubnetName: !Select [ 1, !Ref SubnetPrivateNames ]
        VpcId: !GetAtt VpcStack.Outputs.VpcId

Outputs:
  VpcId:
    Description: "Id of the VPC"
    Value: !GetAtt VpcStack.Outputs.VpcId
  VpcCidrBlock:
    Description: "Cidr of the VPC"
    Value: !GetAtt VpcStack.Outputs.VpcCidrBlock
  SubnetPublicId:
    Description: "Id of the Public Subnet"
    Value: !GetAtt SubnetPublicStack.Outputs.SubnetId
  SubnetPublicCidr:
    Description: "Cidr of the Public Subnet"
    Value: !GetAtt SubnetPublicStack.Outputs.SubnetCidrBlock
  SubnetPrivateIds:
    Description: "Id of the Private Subnets"
    Value: !Join 
      - ","
      - - !GetAtt SubnetPrivateAStack.Outputs.SubnetId
        - !GetAtt SubnetPrivateBStack.Outputs.SubnetId
  SubnetPrivateCidrs:
    Description: "Cidr of the Private Subnets"
    Value: !Join
      - ","
      - - !GetAtt SubnetPrivateAStack.Outputs.SubnetCidrBlock
        - !GetAtt SubnetPrivateBStack.Outputs.SubnetCidrBlock